import type { CasePacket } from './types'

export const CASE_RECONSTRUCTION_DEMO_CASE: CasePacket = {
  id: 'recon-ledger-lodge',
  title: '山庄账本案',
  difficulty: 'medium',
  estimatedMinutes: 15,
  playerRole: '调查记录员',
  sceneZero: {
    openingMoment: '暴雪封路的山庄书房里，馆长林伯言倒在展示柜旁。主电路刚恢复，房门从内侧反锁。',
    playerRole: '调查记录员',
    initialKnownFactIds: [
      'fact-door-locked',
      'fact-time-of-death',
      'fact-blackout-window',
      'fact-donor-announcement',
    ],
    startingLeads: [
      { id: 'witness-chen', label: '陈筝，馆长助理', type: 'witness' },
      { id: 'witness-song', label: '宋策，山庄管家', type: 'witness' },
      { id: 'evidence-autopsy', label: '初步尸检记录', type: 'evidence' },
      { id: 'evidence-generator-log', label: '备用发电机日志', type: 'evidence' },
    ],
    cautionNote: '先不要急着交卷，当前关于动机和凶器的证据明显不足。',
  },
  motives: [
    { id: 'motive-coverup-theft', label: '掩盖挪用公款', summary: '馆长准备公开账本，凶手为掩盖资金去向先下手。' },
    { id: 'motive-jealousy', label: '私人嫉妒', summary: '围绕亲密关系和受偏爱引发的报复。' },
    { id: 'motive-inheritance', label: '争夺遗产', summary: '为了继承即将变更的资产安排而作案。' },
  ],
  facts: [
    { id: 'fact-door-locked', label: '房门反锁', summary: '书房主门从内侧反锁，第一发现人是破窗后进入。', tier: 'surface', category: 'access', source: 'scene_zero' },
    { id: 'fact-time-of-death', label: '死亡时间', summary: '馆长死亡时间被锁定在 20:52 到 20:56 之间。', tier: 'surface', category: 'timeline', source: 'scene_zero' },
    { id: 'fact-blackout-window', label: '停电窗口', summary: '山庄在 20:51 到 20:54 之间发生了短暂断电。', tier: 'surface', category: 'timeline', source: 'scene_zero' },
    { id: 'fact-donor-announcement', label: '捐赠名单', summary: '馆长原计划当晚宣布新的修缮捐赠名单。', tier: 'surface', category: 'context', source: 'scene_zero' },
    { id: 'fact-argument-before-blackout', label: '停电前争执', summary: '停电前几分钟，馆长曾在书房内和陈筝激烈争执。', tier: 'gated', category: 'timeline', source: 'witness', gateId: 'gate-two-evidence' },
    { id: 'fact-master-key-access', label: '备用钥匙权限', summary: '陈筝的值班权限能调出书房展示柜与备用钥匙抽屉。', tier: 'gated', category: 'access', source: 'evidence', gateId: 'gate-three-evidence' },
    { id: 'fact-panel-switched-manually', label: '停电被人为触发', summary: '停电不是故障，而是有人手动关闭了配电面板。', tier: 'gated', category: 'means', source: 'evidence', gateId: 'gate-three-evidence' },
    { id: 'fact-chen-near-panel', label: '陈筝靠近配电间', summary: '停电前后一分钟内，有人看见陈筝从配电间方向折返。', tier: 'gated', category: 'alibi', source: 'witness', gateId: 'gate-core-fact' },
    { id: 'fact-ledger-exposes-theft', label: '账本暴露漏洞', summary: '捐赠账本能直接指向陈筝私自挪用了修缮款。', tier: 'gated', category: 'motive', source: 'evidence', gateId: 'gate-core-fact' },
    { id: 'fact-chisel-cleaned', label: '凶器被清洗归位', summary: '真正的凶器是展柜工具凿，作案后被擦拭并放回原处。', tier: 'hidden', category: 'means', source: 'analysis', gateId: 'gate-hidden' },
  ],
  evidence: [
    { id: 'evidence-autopsy', label: '初步尸检记录', kind: 'forensic', summary: '确认致命伤来自钝尖工具，死亡时间落在断电窗口内。', supportsFactIds: ['fact-time-of-death'] },
    { id: 'evidence-generator-log', label: '备用发电机日志', kind: 'digital', summary: '日志显示停电为人工切断，而非自然故障。', supportsFactIds: ['fact-panel-switched-manually'] },
    { id: 'evidence-audio-fragment', label: '录音残片', kind: 'digital', summary: '录到馆长提到账目和“今晚就公开”的争执片段。', supportsFactIds: ['fact-argument-before-blackout'] },
    { id: 'evidence-keycard-scan', label: '值班权限记录', kind: 'document', summary: '值班系统记录陈筝在案发前调阅过展柜和备用钥匙权限。', supportsFactIds: ['fact-master-key-access'] },
    { id: 'evidence-ledger-page', label: '账本撕页复印件', kind: 'document', summary: '复原后的账页显示陈筝负责的款项有明显缺口。', supportsFactIds: ['fact-ledger-exposes-theft'] },
    { id: 'evidence-metal-residue', label: '金属残留擦痕', kind: 'forensic', summary: '展示凿边缘有新近擦拭痕迹，血迹残留不足但金属碎屑吻合伤口。', supportsFactIds: ['fact-chisel-cleaned'] },
    { id: 'evidence-pocket-watch', label: '停摆怀表', kind: 'physical', summary: '死者怀表停在 20:43，但内部进水更早，无法直接作为死亡时间依据。', supportsFactIds: [], isRedHerring: true },
    { id: 'evidence-caretaker-note', label: '管家便签', kind: 'document', summary: '便签记录了晚餐后有人临时要求进入配电间，但未写明姓名。', supportsFactIds: [], isRedHerring: true },
  ],
  witnesses: [
    {
      id: 'witness-chen',
      name: '陈筝',
      role: 'suspect',
      publicProfile: '馆长助理，负责修缮捐赠对接，最近情绪紧绷。',
      demeanor: 'guarded',
      testimony: [
        {
          id: 'testimony-chen-1',
          promptLabel: '她和馆长最后一次谈了什么？',
          summary: '陈筝承认两人谈到账目，但坚称只是工作分歧。',
          revealsFactIds: ['fact-argument-before-blackout'],
          unlockGateId: 'gate-two-evidence',
        },
        {
          id: 'testimony-chen-2',
          promptLabel: '她为什么能接触展柜与钥匙？',
          summary: '她说是为了核对明天的布展清单，否认动过备用钥匙。',
          revealsFactIds: ['fact-master-key-access'],
          unlockGateId: 'gate-three-evidence',
        },
      ],
    },
    {
      id: 'witness-song',
      name: '宋策',
      role: 'witness',
      publicProfile: '山庄管家，熟悉电路与巡楼路线。',
      demeanor: 'cooperative',
      testimony: [
        {
          id: 'testimony-song-1',
          promptLabel: '停电时谁最可疑？',
          summary: '宋策说停电后他在走廊见到陈筝从配电间方向折返。',
          revealsFactIds: ['fact-chen-near-panel'],
          unlockGateId: 'gate-core-fact',
        },
      ],
    },
    {
      id: 'witness-qin',
      name: '秦望',
      role: 'witness',
      publicProfile: '受邀采访的记者，当晚原计划报道馆长的新捐赠名单。',
      demeanor: 'evasive',
      testimony: [
        {
          id: 'testimony-qin-1',
          promptLabel: '馆长为什么急着公开名单？',
          summary: '秦望听到馆长说“账目今晚不说清，明天就来不及了”。',
          revealsFactIds: ['fact-ledger-exposes-theft'],
          unlockGateId: 'gate-core-fact',
        },
      ],
    },
  ],
  revealGates: [
    {
      id: 'gate-two-evidence',
      label: '至少发现 2 条证据后，才能问出停电前争执。',
      type: 'evidence_count',
      threshold: 2,
      unlocksFactIds: ['fact-argument-before-blackout'],
    },
    {
      id: 'gate-three-evidence',
      label: '至少发现 3 条证据后，才能锁定权限和停电手法。',
      type: 'evidence_count',
      threshold: 3,
      unlocksFactIds: ['fact-master-key-access', 'fact-panel-switched-manually'],
    },
    {
      id: 'gate-core-fact',
      label: '当停电手法成立后，才能推出配电间目击与真实动机。',
      type: 'fact_discovered',
      requiredFactIds: ['fact-panel-switched-manually'],
      unlocksFactIds: ['fact-chen-near-panel', 'fact-ledger-exposes-theft'],
      unlocksWitnessIds: ['witness-song', 'witness-qin'],
    },
    {
      id: 'gate-hidden',
      label: '当动机与权限都成立时，隐藏凶器细节才可被验证。',
      type: 'fact_discovered',
      requiredFactIds: ['fact-master-key-access', 'fact-ledger-exposes-theft'],
      unlocksFactIds: ['fact-chisel-cleaned'],
    },
  ],
  groundTruth: {
    culpritId: 'witness-chen',
    motiveId: 'motive-coverup-theft',
    timelineFactIds: [
      'fact-donor-announcement',
      'fact-argument-before-blackout',
      'fact-panel-switched-manually',
      'fact-time-of-death',
      'fact-chisel-cleaned',
    ],
    decisiveEvidencePairs: [
      { evidenceId: 'evidence-audio-fragment', factId: 'fact-argument-before-blackout' },
      { evidenceId: 'evidence-generator-log', factId: 'fact-panel-switched-manually' },
      { evidenceId: 'evidence-keycard-scan', factId: 'fact-master-key-access' },
      { evidenceId: 'evidence-ledger-page', factId: 'fact-ledger-exposes-theft' },
      { evidenceId: 'evidence-metal-residue', factId: 'fact-chisel-cleaned' },
    ],
    requiredFactIds: [
      'fact-panel-switched-manually',
      'fact-master-key-access',
      'fact-ledger-exposes-theft',
      'fact-chisel-cleaned',
    ],
  },
  validation: {
    successThreshold: 60,
    hiddenThreshold: 80,
    optimalThreshold: 90,
    minimumEvidencePairs: 3,
    minimumTimelineFacts: 4,
    checkpointThresholds: {
      evidenceCount: 5,
      coreFactsDiscovered: 3,
    },
    weights: {
      culprit: 35,
      timeline: 25,
      evidence: 25,
      motive: 15,
      total: 100,
    },
  },
}
