"""MMS 来源/adapter registry.

这个文件不直接驱动运行时逻辑，主要承担两件事：
1. 记录当前默认维护的前 10 个来源公司/品牌。
2. 固化后续新增 adapter 的默认策略，避免继续靠聊天记录传递约定。
"""

from __future__ import annotations

TOP_SOURCE_COMPANIES = [
    {
        "id": "anthropic-claude",
        "company": "Anthropic",
        "brand": "Claude",
        "families": ["claude-*"],
        "source_kind": "official_cli",
        "oauth_native": True,
        "default_adapter": "official_native",
        "claude_bridge_default": False,
        "current_support": "native",
        "notes": "Claude 自己就是目标 CLI，不需要反向 bridge。",
        "references": [
            "https://www.anthropic.com/claude-code",
            "https://docs.anthropic.com/en/docs/claude-code/quickstart",
        ],
    },
    {
        "id": "openai-gpt-codex",
        "company": "OpenAI",
        "brand": "GPT / Codex",
        "families": ["gpt-*", "o*", "codex-*"],
        "source_kind": "official_cli",
        "oauth_native": True,
        "default_adapter": "official_native+claude_bridge",
        "claude_bridge_default": True,
        "current_support": "native+bridge",
        "notes": "当前已支持 codex 官方账号直启，也支持留在 claude 的官方桥接。",
        "references": [
            "https://developers.openai.com/codex/cli",
        ],
    },
    {
        "id": "google-gemini",
        "company": "Google",
        "brand": "Gemini",
        "families": ["gemini-*"],
        "source_kind": "official_cli",
        "oauth_native": True,
        "default_adapter": "official_native+claude_bridge",
        "claude_bridge_default": True,
        "current_support": "native+bridge",
        "notes": "当前通过 gemini-cli-core/CodeAssistServer 做 claude bridge。",
        "references": [
            "https://google-gemini.github.io/gemini-cli/docs/tools/code/",
        ],
    },
    {
        "id": "qwen",
        "company": "Alibaba Cloud",
        "brand": "Qwen",
        "families": ["qwen-*", "qwen3-*"],
        "source_kind": "provider_api",
        "oauth_native": False,
        "default_adapter": "provider_api",
        "claude_bridge_default": False,
        "current_support": "provider",
        "notes": "当前优先按 OpenAI-compatible provider 接入；未确认稳定的官方 CLI/OAuth bridge 路径。",
        "references": [
            "https://qwen.ai/",
            "https://coder.qwen.ai/",
        ],
    },
    {
        "id": "moonshot-kimi",
        "company": "Moonshot AI",
        "brand": "Kimi",
        "families": ["kimi-*", "kimi-for-coding"],
        "source_kind": "hybrid",
        "oauth_native": True,
        "default_adapter": "provider_api",
        "claude_bridge_default": True,
        "current_support": "provider",
        "notes": "官方有 Kimi Code CLI / login，但 MMS 当前默认仍按 provider_api 落地，后续可补 OAuth adapter。",
        "references": [
            "https://www.kimi.com/coding/en",
            "https://www.kimi.com/coding/docs/en/",
            "https://www.kimi.com/code/docs/en/third-party-agents.html",
        ],
    },
    {
        "id": "minimax-cn",
        "company": "MiniMax",
        "brand": "MiniMax CN",
        "families": ["minimax-*", "minimax-m*"],
        "source_kind": "provider_api",
        "oauth_native": False,
        "default_adapter": "provider_api",
        "claude_bridge_default": False,
        "current_support": "planned-provider",
        "notes": "国内套餐/Agent 能力强，但当前更适合走 provider/API，而不是 OAuth bridge。",
        "references": [
            "https://www.minimax.io/news/mini-pricemax-performance%E5%85%B3%E4%BA%8Eapi%E7%BC%96%E7%A8%8B%E5%A5%97%E9%A4%90%E5%92%8Cagent",
            "https://www.minimax.io/news/m21-coding-%E5%A4%9A%E8%AF%AD%E8%A8%80%E5%A4%9A%E4%BB%BB%E5%8A%A1%E4%B8%8E%E6%B3%9B%E5%8C%96%E6%80%A7",
        ],
    },
    {
        "id": "minimax-en",
        "company": "MiniMax",
        "brand": "MiniMax EN",
        "families": ["minimax-*", "minimax-m*"],
        "source_kind": "provider_api",
        "oauth_native": False,
        "default_adapter": "provider_api",
        "claude_bridge_default": False,
        "current_support": "planned-provider",
        "notes": "国际站模型与品牌单独记录，后续接 provider 时可区分中英文环境。",
        "references": [
            "https://www.minimax.io/en",
            "https://www.minimax.io/news/minimax-m2",
            "https://www.minimax.io/news/minimax-m25",
        ],
    },
    {
        "id": "zai-glm",
        "company": "Z.ai",
        "brand": "GLM (Z.ai)",
        "families": ["glm-*"],
        "source_kind": "provider_api",
        "oauth_native": False,
        "default_adapter": "provider_api",
        "claude_bridge_default": False,
        "current_support": "planned-provider",
        "notes": "官方强调对 Claude Code/Cline 兼容，当前最适合做 provider 入口。",
        "references": [
            "https://docs.z.ai/",
            "https://docs.z.ai/guides/llm/glm-4.6",
            "https://docs.z.ai/devpack/extension/usage-query-plugin",
        ],
    },
    {
        "id": "bigmodel-glm",
        "company": "BigModel / 智谱",
        "brand": "GLM (BigModel)",
        "families": ["glm-*"],
        "source_kind": "provider_api",
        "oauth_native": False,
        "default_adapter": "provider_api",
        "claude_bridge_default": False,
        "current_support": "planned-provider",
        "notes": "官方已提供 Claude-compatible 与 OpenAI-compatible 文档，适合作为 provider。",
        "references": [
            "https://docs.bigmodel.cn/cn/guide/develop/claude/introduction",
            "https://docs.bigmodel.cn/cn/guide/develop/openai/introduction",
            "https://docs.bigmodel.cn/",
        ],
    },
    {
        "id": "volcengine-doubao",
        "company": "Volcengine / 火山引擎",
        "brand": "Doubao / Ark",
        "families": ["doubao-*", "seed-*"],
        "source_kind": "provider_api",
        "oauth_native": False,
        "default_adapter": "provider_api",
        "claude_bridge_default": False,
        "current_support": "planned-provider",
        "notes": "当前先按方舟/豆包 provider 评估；未确认稳定的官方 CLI/OAuth bridge 路径。",
        "references": [
            "https://www.volcengine.com/",
            "https://developer.volcengine.com/",
        ],
    },
]


DEFAULT_ADAPTER_POLICY = {
    "official_oauth": "如果某个来源存在稳定的官方 CLI/SDK/backend，新增 OAuth adapter 时默认同时补 claude_bridge。",
    "provider_api": "如果某个来源没有稳定的原生 CLI/OAuth 路径，默认按 provider_api 接入，而不是强做 bridge。",
    "runtime_boundary": "官方账号是运行入口，provider 是模型源；只有在 bridge 存在时，官方账号才可在 claude 中复用。",
    "selection_boundary": "明确选了具体模型时，只展示真正能承载该模型的来源，不把所有官方账号混进来。",
}


PROVIDER_TEMPLATES = {
    "generic": {
        "id": "default",
        "name": "My Gateway",
        "protocols": ["anthropic_messages", "openai_chat_completions"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 100,
        "note": "通用兼容网关，适合自建或聚合 API。",
    },
    "qwen": {
        "id": "qwen",
        "name": "Qwen",
        "protocols": ["openai_chat_completions", "anthropic_messages"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 80,
        "default_openai_base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "default_anthropic_base_url": "https://dashscope.aliyuncs.com/apps/anthropic",
        "note": "Qwen / Qwen Code 来源模板，同时支持 OpenAI 和 Anthropic 协议。",
    },
    "bailian-codingplan": {
        "id": "bailian-codingplan",
        "name": "百炼 CodingPlan",
        "protocols": ["openai_chat_completions", "anthropic_messages"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 75,
        "default_openai_base_url": "https://coding.dashscope.aliyuncs.com/v1",
        "default_anthropic_base_url": "https://coding.dashscope.aliyuncs.com/apps/anthropic",
        "key_prefix": "sk-sp-",
        "fallback_models": [
            "qwen3.5-plus", "qwen3-max-2026-01-23",
            "qwen3-coder-next", "qwen3-coder-plus",
            "glm-5", "glm-4.7",
            "kimi-k2.5", "MiniMax-M2.5",
        ],
        "note": "阿里百炼 CodingPlan 套餐 (sk-sp-* key)，多厂商模型聚合，同时支持 OpenAI 和 Anthropic 协议。",
    },
    "kimi": {
        "id": "kimi",
        "name": "Kimi",
        "protocols": ["openai_chat_completions", "anthropic_messages"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 80,
        "default_openai_base_url": "https://api.moonshot.cn/v1",
        "default_anthropic_base_url": "https://api.moonshot.ai/anthropic/",
        "note": "Kimi / Moonshot 来源模板，同时支持 OpenAI（.cn）和 Anthropic（.ai）协议。",
    },
    "kimi-codingplan": {
        "id": "kimi-codingplan",
        "name": "Kimi CodingPlan",
        "protocols": ["openai_chat_completions", "anthropic_messages"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 75,
        "default_openai_base_url": "https://api.kimi.com/coding/v1",
        "default_anthropic_base_url": "https://api.kimi.com/coding/",
        "key_prefix": "sk-kimi-",
        "note": "Kimi CodingPlan 套餐 (sk-kimi-* key)，同时支持 OpenAI 和 Anthropic 协议。",
    },
    "glm-en": {
        "id": "glm-en",
        "name": "GLM EN (Z.ai)",
        "protocols": ["anthropic_messages", "openai_chat_completions"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 85,
        "default_openai_base_url": "https://api.z.ai/api/paas/v4/",
        "default_anthropic_base_url": "https://api.z.ai/api/anthropic",
        "note": "Z.ai / GLM 国际来源模板，OpenAI 与 Anthropic 端点分离。",
    },
    "glm-cn": {
        "id": "glm-cn",
        "name": "GLM CN (BigModel)",
        "protocols": ["anthropic_messages", "openai_chat_completions"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 85,
        "default_openai_base_url": "https://open.bigmodel.cn/api/paas/v4/",
        "default_anthropic_base_url": "https://open.bigmodel.cn/api/anthropic",
        "note": "智谱 BigModel / GLM 国内来源模板，OpenAI 与 Anthropic 端点分离。",
    },
    "minimax-cn": {
        "id": "minimax-cn",
        "name": "MiniMax CN",
        "protocols": ["anthropic_messages", "openai_chat_completions"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 85,
        "default_openai_base_url": "https://api.minimaxi.com/v1",
        "default_anthropic_base_url": "https://api.minimaxi.com/anthropic",
        "fallback_models": [
            "MiniMax-M2.5", "MiniMax-M2.5-highspeed", "MiniMax-M2.1", "MiniMax-M2",
        ],
        "note": "MiniMax 国内来源模板，OpenAI 与 Anthropic 端点分离。",
    },
    "minimax-codingplan": {
        "id": "minimax-codingplan",
        "name": "MiniMax CodingPlan",
        "protocols": ["openai_chat_completions", "anthropic_messages"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 75,
        "default_openai_base_url": "https://api.minimax.chat/v1",
        "default_anthropic_base_url": "https://api.minimaxi.com/anthropic",
        "note": "MiniMax CodingPlan 套餐，Anthropic 端点共用 minimaxi.com。",
    },
    "minimax-en": {
        "id": "minimax-en",
        "name": "MiniMax EN",
        "protocols": ["anthropic_messages", "openai_chat_completions"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 85,
        "default_openai_base_url": "https://api.minimax.io/v1",
        "default_anthropic_base_url": "https://api.minimax.io/anthropic",
        "note": "MiniMax 国际来源模板，OpenAI 与 Anthropic 端点分离。",
    },
    "zai-glm": {
        "id": "glm-en",
        "name": "GLM EN (Z.ai)",
        "protocols": ["anthropic_messages", "openai_chat_completions"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 85,
        "default_openai_base_url": "https://api.z.ai/api/paas/v4/",
        "default_anthropic_base_url": "https://api.z.ai/api/anthropic",
        "note": "兼容旧名字的别名模板，实际等同于 glm-en。",
    },
    "bigmodel-glm": {
        "id": "glm-cn",
        "name": "GLM CN (BigModel)",
        "protocols": ["anthropic_messages", "openai_chat_completions"],
        "supported_clis": ["claude", "codex", "qwen", "kimi"],
        "priority": 85,
        "default_openai_base_url": "https://open.bigmodel.cn/api/paas/v4/",
        "default_anthropic_base_url": "https://open.bigmodel.cn/api/anthropic",
        "note": "兼容旧名字的别名模板，实际等同于 glm-cn。",
    },
}
