# -*- coding: utf-8 -*-
"""TUI-to-WebUI Settings coverage maps for the MMS config WebUI."""

from __future__ import annotations

from typing import Any

from mms_config.web_common import _safe_text


def _webui_capability_coverage() -> list[dict[str, str]]:
    return [
        {
            "area": "通道",
            "capability": "provider 新增/编辑/默认/role/priority/Base URL/API Key/protocol/CLI/timezone/note/Claude 1M",
            "webui": "native",
            "tui": "webui_primary_removed_from_settings_top_level",
        },
        {
            "area": "通道",
            "capability": "模型拉取、手动 extra_models、hidden_models、能力标签",
            "webui": "native",
            "tui": "can_degrade_after_route_guard_verified",
        },
        {
            "area": "通道",
            "capability": "本地使用统计 / 最近使用 / 健康覆盖层",
            "webui": "read_only_detail_report",
            "tui": "can_degrade_after_report_smoke",
        },
        {
            "area": "账号",
            "capability": "CLI account 默认值、启用状态、priority、metadata、timezone、note；OAuth 登录主流程下线",
            "webui": "draft_review_human_gate",
            "tui": "keep_emergency_only_for_remove_and_claude_human_gate",
        },
        {
            "area": "设置",
            "capability": "Registry 源状态、preview doctor、Bundle、就绪度和状态",
            "webui": "read_only_reports_plus_existing_apply",
            "tui": "can_degrade_report_display_after_webui_smoke",
        },
        {
            "area": "设置",
            "capability": "Snapshot Guard 接受基线 / 真实配置 drift 确认",
            "webui": "manual_cli_human_gate",
            "tui": "keep_until_webui_double_confirm_flow_exists",
        },
        {
            "area": "设置",
            "capability": "Rescue fallback 配置",
            "webui": "native",
            "tui": "can_degrade_config_display_after_save_flow_verified",
        },
        {
            "area": "设置",
            "capability": "Rescue packet 浏览 / fallback 交接",
            "webui": "read_only_report",
            "tui": "keep_emergency_only_until_handover_write_flow_exists",
        },
        {
            "area": "设置",
            "capability": "界面语言和关于/版本检查",
            "webui": "report_or_planned",
            "tui": "keep_small",
        },
        {
            "area": "主屏入口",
            "capability": "O 接入 / P 通道 / S 设置入口覆盖状态",
            "webui": "module_native_controls_plus_reports",
            "tui": "keep_as_keyboard_launcher_until_webui_launch_surface_exists",
        },
    ]


def _tui_webui_mapping() -> list[dict[str, str]]:
    """Trace every Settings/Channel TUI action to its WebUI destination."""

    def row(
        row_id: str,
        *,
        tui_area: str,
        tui_action_id: str,
        tui_label: str,
        webui_section: str,
        webui_control: str,
        status: str,
        write_policy: str,
        verification: str,
        manual_check: str,
        webui_section_id: str = "",
        api_action: str = "",
    ) -> dict[str, str]:
        click_targets = []
        if webui_section_id:
            click_targets.append("open_section")
        if api_action:
            click_targets.append("settings_report")
        if status in {"native", "draft_review"}:
            click_targets.append("save_preview")
        if status == "human_gate":
            click_targets.append("human_gate_card")
        if status == "missing":
            click_targets.append("missing_gap")
        click_text = " + ".join(dict.fromkeys(click_targets))
        if status == "human_gate":
            acceptance_check = "点人工确认查看风险/写入范围/命令；只复制命令，不在 WebUI 自动执行。"
        elif status == "report":
            acceptance_check = "点报告确认 API 返回 ok/只读 JSON。"
        elif status == "draft_review":
            acceptance_check = "编辑草稿后生成保存预览，确认审查摘要和 diff。"
        elif status == "native":
            acceptance_check = "点打开 WebUI 落点；如修改配置，继续生成保存预览确认。"
        else:
            acceptance_check = "必须补 WebUI 落点或显式 gate，不允许隐藏。"
        return {
            "id": row_id,
            "tui_area": tui_area,
            "tui_action_id": tui_action_id,
            "tui_label": tui_label,
            "webui_section": webui_section,
            "webui_section_id": webui_section_id,
            "webui_control": webui_control,
            "api_action": api_action,
            "status": status,
            "write_policy": write_policy,
            "verification": verification,
            "manual_check": manual_check,
            "clickable": "yes" if webui_section_id or api_action else "no",
            "click_targets": click_text,
            "acceptance_check": acceptance_check,
        }

    rows = [
        row(
            "connect.add_gateway",
            tui_area="Main / O 接入",
            tui_action_id="connect_gateway",
            tui_label="添加网关通道",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="添加通道按钮 + 通道编辑器 + 保存预览",
            api_action="connect_gateway_status",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="/api/plan provider_added + save review",
            manual_check="WebUI 新增 provider 后仍需保存预览，不直接写真实配置。",
        ),
        row(
            "connect.add_official",
            tui_area="Main / O 接入",
            tui_action_id="connect_official",
            tui_label="添加官方通道 / OAuth 登录",
            webui_section="Settings / 兼容说明",
            webui_section_id="settings",
            webui_control="OAuth/AGY 官方登录已从 WebUI 主流程下线；仅保留只读兼容说明",
            api_action="connect_official_gate",
            status="report",
            write_policy="deprecated_read_only_compat",
            verification="/api/settings/report?action=connect_official_gate",
            manual_check="新配置使用 API Key 通道；旧 OAuth/AGY 账号只做兼容查看，不再作为新增入口。",
        ),
        row(
            "connect.manage_channels",
            tui_area="Main / O 接入",
            tui_action_id="manage_channels",
            tui_label="管理现有通道",
            webui_section="通道配置 + Settings / 账号",
            webui_section_id="channel",
            webui_control="通道编辑器 + 账号表模块动作",
            api_action="tui_mapping",
            status="native",
            write_policy="mixed_draft_review_human_gate",
            verification="/api/settings/report?action=tui_mapping",
            manual_check="网关通道 native；官方账号危险动作 需要人工确认。",
        ),
        row(
            "connect.migrate_config",
            tui_area="Main / O 接入",
            tui_action_id="migrate_config",
            tui_label="迁移配置到 mms",
            webui_section="能力整合",
            webui_section_id="settings",
            webui_control="迁移人工确认报告",
            api_action="migrate_config_gate",
            status="human_gate",
            write_policy="manual_cli_human_gate",
            verification="/api/settings/report?action=migrate_config_gate",
            manual_check="迁移会读写真实配置树，必须人工执行/确认。",
        ),
        row(
            "channel.provider_browse",
            tui_area="Main / P 通道",
            tui_action_id="provider_browse",
            tui_label="浏览 / 选择通道",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="通道列表、使用统计标签、默认值和 priority 字段",
            api_action="provider_usage_summary",
            status="report",
            write_policy="read_only_report",
            verification="/api/settings/report?action=provider_usage_summary",
            manual_check="启动时选择仍属于 launcher；配置侧状态已在 WebUI 可见。",
        ),
        row(
            "channel.provider_switch",
            tui_area="Model / Channel column",
            tui_action_id="←/→ focus + Enter provider override",
            tui_label="模型页切换通道来源",
            webui_section="通道配置 + Runtime",
            webui_section_id="channel",
            webui_control="默认通道、priority 字段、runtime/opencode 模型选择器",
            api_action="provider_channel_status",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="/api/plan provider_default/priority/runtime diffs",
            manual_check="WebUI 做持久配置；TUI 的单次启动选择仍保留为 launcher 能力。",
        ),
        row(
            "channel.priority_adjust",
            tui_area="Model / Channel column",
            tui_action_id="+/- priority_changes",
            tui_label="调整通道权重",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="通道 priority + family_priority_overrides 字段 + 保存预览",
            api_action="provider_channel_status",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="/api/plan provider priority/family override diff",
            manual_check="全局 priority 与 family_priority_overrides 都进入 WebUI 草稿和保存预览。",
        ),
        row(
            "channel.family_autosort",
            tui_area="Model / Channel column",
            tui_action_id="A auto rank",
            tui_label="按 speed stats 智能排序",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="通道报告与确认 tab 的自动排序用途说明",
            api_action="family_autosort_gate",
            status="human_gate",
            write_policy="speed_stats_write_human_gate",
            verification="/api/settings/report?action=family_autosort_gate",
            manual_check="自动排序会批量改 priority/family override；WebUI 当前只展示用途和人工确认说明，不静默改顺序。",
        ),
        row(
            "settings.provider_mgmt",
            tui_area="Settings (WebUI-only)",
            tui_action_id="webui_only:provider_mgmt",
            tui_label="Provider 管理（WebUI-only）",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="左侧通道列表、通道配置 tab、模型配置 tab、保存审计",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="/api/plan diff + /api/save or /api/registry-v2/apply",
            manual_check="TUI 顶层不再提供 provider 快调；检查 provider add/edit/default/model list 是否都能进入保存预览。",
        ),
        row(
            "settings.account_mgmt",
            tui_area="Settings (WebUI/CLI emergency)",
            tui_action_id="webui_only:account_mgmt",
            tui_label="账号管理（WebUI/CLI）",
            webui_section="Settings / 账号",
            webui_section_id="settings",
            webui_control="账号 / OAuth 通道表 + 非 Claude account 草稿",
            api_action="accounts",
            status="draft_review",
            write_policy="draft_review_human_gate",
            verification="/api/settings/report?action=accounts redacts home_dir/proxy",
            manual_check="非 Claude account 可改 name/enabled/priority/default；Claude/login/remove 保持锁定。",
        ),
        row(
            "settings.registry",
            tui_area="Settings (WebUI/CLI emergency)",
            tui_action_id="webui_only:registry",
            tui_label="模型源状态（WebUI/CLI）",
            webui_section="配置源状态",
            webui_section_id="source",
            webui_control="配置源状态 卡片 + 报告按钮 + 保存 / 应用流程",
            api_action="model_source_status",
            status="report",
            write_policy="read_only_report",
            verification="/api/settings/report?action=model_source_status",
            manual_check="写入类 registry 操作必须继续走 save/apply 人工确认。",
        ),
        row(
            "settings.guard",
            tui_area="Settings (WebUI/CLI emergency)",
            tui_action_id="webui_only:guard",
            tui_label="启动快照（WebUI/CLI）",
            webui_section="Settings / Snapshot Guard",
            webui_section_id="settings",
            webui_control="Snapshot 快照状态 / 人工确认报告",
            api_action="guard_accept_gate",
            status="human_gate",
            write_policy="manual_cli_human_gate",
            verification="/api/settings/report?action=guard_accept_gate",
            manual_check="accept 不自动执行；必须 human double-confirm。",
        ),
        row(
            "settings.rescue",
            tui_area="Settings",
            tui_action_id="rescue",
            tui_label="中断/救援",
            webui_section="Fallback",
            webui_section_id="fallback",
            webui_control="rescue fallback / hot fallback 表单 + rescue 事件报告",
            api_action="rescue_events",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="fallback form feeds /api/plan; events use /api/settings/report?action=rescue_events",
            manual_check="fallback 写入前必须生成保存预览；packet handover 仍未自动写。",
        ),
        row(
            "settings.language",
            tui_area="Settings",
            tui_action_id="language",
            tui_label="界面语言",
            webui_section="Settings / 界面语言",
            webui_section_id="settings",
            webui_control="界面语言选择器 + 保存审计",
            api_action="language_status",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="/api/settings/report?action=language_status",
            manual_check="语言变化进入 /api/plan diff；不直接写真实 config。",
        ),
        row(
            "settings.routes_export",
            tui_area="Settings (WebUI/CLI emergency)",
            tui_action_id="webui_only:routes_export",
            tui_label="Legacy 路由导出（WebUI/CLI）",
            webui_section="保存 / 审计",
            webui_section_id="save",
            webui_control="生成保存预览、stable 审计保存、preview DB 发布",
            api_action="routes_export",
            status="native",
            write_policy="save_flow_or_preview_publish",
            verification="/api/plan + /api/save or /api/registry-v2/apply",
            manual_check="直接导出按钮不单独暴露；保存/发布流负责 routes artifacts。",
        ),
        row(
            "settings.about",
            tui_area="Settings",
            tui_action_id="about",
            tui_label="关于",
            webui_section="Settings / 关于",
            webui_section_id="settings",
            webui_control="关于状态",
            api_action="about",
            status="report",
            write_policy="read_only_report",
            verification="/api/settings/report?action=about",
            manual_check="upgrade 动作仍是 manual CLI/人工确认。",
        ),
        row(
            "provider.local_usage",
            tui_area="Channel / Provider",
            tui_action_id="provider:1",
            tui_label="查看本地统计",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="通道列表使用统计标签 + 使用统计报告",
            api_action="provider_usage_summary",
            status="report",
            write_policy="read_only_report",
            verification="/api/settings/report?action=provider_usage_summary",
            manual_check="WebUI report 返回 TUI 同等 CLI/启动次数/最近模型/最近使用明细。",
        ),
        row(
            "provider.models",
            tui_area="Channel / Provider",
            tui_action_id="provider:2",
            tui_label="模型管理",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="模型配置 tab、拉取模型、extra_models、hidden_models、能力开关",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="/api/provider/models + /api/plan",
            manual_check="检查模型拉取、隐藏/补充、capability toggle、stale cleanup。",
        ),
        row(
            "provider.model_patch_reset",
            tui_area="Channel / Provider",
            tui_action_id="provider:2/model:6",
            tui_label="恢复默认模型补丁",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="模型配置 tab 恢复模型补丁按钮",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="/api/plan extra_models/hidden_models diff",
            manual_check="一键清空当前通道 extra_models + hidden_models，然后保存预览。",
        ),
        row(
            "provider.default",
            tui_area="Channel / Provider",
            tui_action_id="provider:3",
            tui_label="设为默认网关",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="设为默认通道复选框",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="/api/plan review_summary.default_provider",
            manual_check="默认 provider 变化必须出现在保存摘要。",
        ),
        row(
            "provider.rename",
            tui_area="Channel / Provider",
            tui_action_id="provider:4",
            tui_label="重命名",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="内部 ID + 显示名字段",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="/api/plan provider rename/remove/add diff",
            manual_check="ID 变化会影响 route scope，必须看 diff。",
        ),
        row(
            "provider.credentials",
            tui_area="Channel / Provider",
            tui_action_id="provider:5",
            tui_label="编辑地址和 Key",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="OpenAI/Anthropic Base URL、models_endpoint、API Key 待保存",
            status="native",
            write_policy="audited_secret_write",
            verification="/api/plan redacts key; save writes audited secret backend",
            manual_check="API Key 只显示 pending，不回显明文。",
        ),
        row(
            "provider.advanced_metadata",
            tui_area="Channel / Provider",
            tui_action_id="provider.edit metadata",
            tui_label="编辑 Claude 1M / timezone / note",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="通道高级 metadata 字段",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="/api/plan provider_metadata review_summary",
            manual_check="TUI provider.edit 的非 secret 元数据进入 WebUI 草稿和保存预览。",
        ),
        row(
            "provider.network_policy",
            tui_area="Channel / Provider",
            tui_action_id="provider.edit proxy/no_proxy",
            tui_label="编辑 proxy / no_proxy",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="通道配置模块里的通道网络策略人工确认",
            api_action="provider_network_gate",
            status="human_gate",
            write_policy="network_policy_human_gate",
            verification="/api/settings/report?action=provider_network_gate",
            manual_check="proxy/no_proxy 可能包含凭据或影响 Claude network policy；WebUI 不回显明文，只给 gate。",
        ),
        row(
            "provider.remove",
            tui_area="Channel / Provider",
            tui_action_id="provider:6",
            tui_label="删除通道",
            webui_section="通道配置",
            webui_section_id="channel",
            webui_control="输入通道 ID 确认 + 保存预览摘要",
            status="native",
            write_policy="draft_review_confirmed_save",
            verification="/api/plan review_summary.provider_removed",
            manual_check="删除只改 WebUI 草稿；真正写入仍需保存预览 + confirm。",
        ),
        row(
            "account.local_usage",
            tui_area="Channel / Account",
            tui_action_id="account:1",
            tui_label="查看本地统计",
            webui_section="Settings / 账号",
            webui_section_id="settings",
            webui_control="账号表使用统计列 + 账号摘要报告",
            api_action="accounts",
            status="report",
            write_policy="read_only_report",
            verification="/api/settings/report?action=accounts",
            manual_check="WebUI accounts report 返回 TUI 同等 CLI/启动次数/最近模型/最近使用明细。",
        ),
        row(
            "account.login",
            tui_area="Channel / Account",
            tui_action_id="account:2",
            tui_label="重新登录",
            webui_section="Settings / 账号",
            webui_section_id="settings",
            webui_control="账号表动作按钮里的登录人工确认",
            api_action="account_login_gate",
            status="human_gate",
            write_policy="manual_login_only",
            verification="/api/settings/report?action=account_login_gate",
            manual_check="登录会碰全局/OAuth 状态，WebUI 不自动执行。",
        ),
        row(
            "account.default",
            tui_area="Channel / Account",
            tui_action_id="account:3",
            tui_label="设为默认官方通道",
            webui_section="Settings / 账号",
            webui_section_id="settings",
            webui_control="非 Claude 默认账号单选按钮",
            api_action="accounts",
            status="draft_review",
            write_policy="draft_review_human_gate",
            verification="/api/plan blocks Claude default and accepts non-Claude default",
            manual_check="Claude default radio disabled；非 Claude 进入保存预览。",
        ),
        row(
            "account.rename",
            tui_area="Channel / Account",
            tui_action_id="account:4",
            tui_label="重命名",
            webui_section="Settings / 账号",
            webui_section_id="settings",
            webui_control="账号表动作按钮里的重命名人工确认",
            api_action="account_rename_gate",
            status="human_gate",
            write_policy="account_home_human_gate",
            verification="/api/settings/report?action=account_rename_gate",
            manual_check="账号重命名会改 home_dir/usage/defaults 并可能移动目录；WebUI 不自动执行。",
        ),
        row(
            "account.edit_metadata",
            tui_area="Channel / Account",
            tui_action_id="account:5",
            tui_label="编辑通道",
            webui_section="Settings / 账号",
            webui_section_id="settings",
            webui_control="非 Claude 名称/启用/priority/family/timezone/Claude 1M/note 草稿字段",
            api_action="accounts",
            status="draft_review",
            write_policy="draft_review_human_gate",
            verification="/api/plan blocks protected fields",
            manual_check="非 Claude metadata 进入 WebUI 保存预览；home_dir/proxy/no_proxy/Claude metadata 仍锁定。",
        ),
        row(
            "account.network_policy",
            tui_area="Channel / Account",
            tui_action_id="account.edit proxy/no_proxy",
            tui_label="编辑账号 proxy / no_proxy",
            webui_section="Settings / 账号",
            webui_section_id="settings",
            webui_control="账号表动作按钮里的网络策略人工确认",
            api_action="account_network_gate",
            status="human_gate",
            write_policy="account_network_human_gate",
            verification="/api/settings/report?action=account_network_gate",
            manual_check="账号 proxy/no_proxy/home_dir 可能涉及 OAuth/Claude protected state；WebUI 不回显明文。",
        ),
        row(
            "account.remove",
            tui_area="Channel / Account",
            tui_action_id="account:6",
            tui_label="删除通道",
            webui_section="Settings / 账号",
            webui_section_id="settings",
            webui_control="账号表动作按钮里的删除人工确认",
            api_action="account_remove_gate",
            status="human_gate",
            write_policy="manual_remove_only",
            verification="/api/settings/report?action=account_remove_gate",
            manual_check="删除账号目录/登录状态必须由 human 手动确认。",
        ),
    ]

    registry_rows = [
        ("registry.model_source_status", "model_source_status", "查看模型源状态状态", "model_source_status", "report", "read_only_report"),
        ("registry.consumer_bundle_status", "consumer_bundle_status", "查看消费端 Bundle", "consumer_bundle_status", "report", "read_only_report"),
        ("registry.v2_save_plan", "registry_v2_save_plan", "查看 v2 保存计划", "", "native", "save_preview"),
        ("registry.config_v2_promotion_plan", "config_v2_promotion_plan", "查看晋级计划", "config_v2_promotion_plan", "report", "read_only_report"),
        ("registry.config_v2_release_readiness", "config_v2_release_readiness", "查看 4.0 就绪度", "config_v2_release_readiness", "report", "read_only_report"),
        ("registry.preview_doctor", "preview_doctor", "运行预览诊断", "preview_doctor", "report", "read_only_report"),
        ("registry.check_staleness", "check_staleness", "检查 source 过期状态", "check_staleness", "report", "read_only_report"),
        ("registry.refresh_due_sources", "refresh_due_sources", "刷新到期 source", "refresh_due_sources_gate", "human_gate", "network_write_human_gate"),
        ("registry.scheduled_dry_run", "scheduled_dry_run", "定时刷新 dry run", "scheduled_refresh_gate", "human_gate", "network_human_gate"),
        ("registry.scheduled_no_network", "scheduled_no_network", "定时刷新 no-network", "scheduled_refresh_gate", "human_gate", "manual_cli_human_gate"),
        ("registry.refresh_sources", "refresh_sources", "刷新全部 source", "refresh_sources_gate", "human_gate", "network_write_human_gate"),
        ("registry.fetch_openrouter", "fetch_openrouter", "拉取 OpenRouter catalog", "fetch_openrouter_gate", "human_gate", "network_human_gate"),
        ("registry.diff_openrouter", "diff_openrouter", "对比 OpenRouter candidate", "diff_openrouter_gate", "human_gate", "network_human_gate"),
        ("registry.publish_approved", "publish_approved", "发布已批准 Bundle", "publish_approved_gate", "human_gate", "write_human_gate"),
        ("registry.verify_approved", "verify_approved", "验证已批准 Bundle", "verify_approved", "report", "read_only_report"),
        ("registry.doctor", "doctor", "Registry 诊断 / 状态", "registry_status", "report", "read_only_report"),
    ]
    for row_id, action_id, label, api_action, status, write_policy in registry_rows:
        manual_check = (
            "只读 manifest/hash 验证，可直接在 WebUI 执行；publish 仍 需要人工确认。"
            if action_id == "verify_approved"
            else "只读项可直接点；network/write 类先人工确认，不静默执行。"
        )
        rows.append(
            row(
                row_id,
                tui_area="Settings / Registry",
                tui_action_id=action_id,
                tui_label=label,
                webui_section="保存 / 审计" if action_id == "registry_v2_save_plan" else "配置源状态",
                webui_section_id="save" if action_id == "registry_v2_save_plan" else "source",
                webui_control="保存页生成保存预览" if action_id == "registry_v2_save_plan" else "配置源状态模块动作按钮",
                api_action=api_action,
                status=status,
                write_policy=write_policy,
                verification=f"/api/settings/report?action={api_action}" if api_action else "/api/plan",
                manual_check=manual_check,
            )
        )

    extra_rows = [
        ("guard.status", "Settings / Snapshot Guard", "status", "查看当前 Snapshot 状态", "guard_status", "report", "read_only_report"),
        ("guard.accept", "Settings / Snapshot Guard", "accept", "接受当前 Snapshot", "guard_accept_gate", "human_gate", "manual_cli_human_gate"),
        ("rescue.default", "Settings / Rescue", "choose_route_default/manual_default", "设置全局默认 fallback", "", "native", "draft_review_confirmed_save"),
        ("rescue.clear_default", "Settings / Rescue", "clear_default", "清除全局默认 fallback", "", "native", "draft_review_confirmed_save"),
        ("rescue.hot_fallback", "Settings / Rescue", "enable_hot_fallback/disable_hot_fallback", "开启/关闭 hot fallback", "", "native", "draft_review_confirmed_save"),
        ("rescue.view_packets", "Settings / Rescue", "view_packets", "查看最近失败 / rescue packet", "rescue_events", "report", "read_only_report"),
        ("rescue.create_demo", "Settings / Rescue", "create_demo", "生成测试 rescue packet", "rescue_create_demo_gate", "human_gate", "local_artifact_human_gate"),
        ("rescue.handover", "Settings / Rescue", "handover/manual_handover", "生成 fallback handover", "rescue_handover_gate", "human_gate", "local_artifact_human_gate"),
        ("rescue.view_md_paths", "Settings / Rescue", "view_md/show_paths", "查看 rescue.md / 显示文件路径", "rescue_events", "report", "read_only_report"),
        ("about.refresh", "Settings / 关于", "refresh_versions", "刷新版本检查", "about_refresh_gate", "human_gate", "network_human_gate"),
        ("about.upgrade", "Settings / 关于", "upgrade_mms/upgrade_codex_cli/upgrade_claude_cli", "升级 MMS / CLI", "about_upgrade_gate", "human_gate", "manual_cli_human_gate"),
    ]
    for row_id, area, action_id, label, api_action, status, write_policy in extra_rows:
        is_rescue = area.endswith("Rescue")
        is_guard = "Snapshot Guard" in area
        is_about = area.endswith("About")
        rows.append(
            row(
                row_id,
                tui_area=area,
                tui_action_id=action_id,
                tui_label=label,
                webui_section="Fallback" if is_rescue else "Settings / Snapshot Guard" if is_guard else "Settings / 关于" if is_about else "Settings",
                webui_section_id="fallback" if is_rescue else "settings",
                webui_control="Fallback 表单 / rescue 动作按钮" if is_rescue else "Snapshot Guard 独立卡片" if is_guard else "关于独立卡片",
                api_action=api_action,
                status=status,
                write_policy=write_policy,
                verification=f"/api/settings/report?action={api_action}" if api_action else "/api/plan",
                manual_check="native 走保存预览；gate/missing 不会伪装成已迁移。",
            )
        )
    return rows


def _tui_webui_mapping_summary(rows: list[dict[str, str]] | None = None) -> dict[str, Any]:
    rows = rows if isinstance(rows, list) else _tui_webui_mapping()
    counts = {"native": 0, "report": 0, "draft_review": 0, "human_gate": 0, "missing": 0}
    clickable = 0
    with_report = 0
    with_open = 0
    for item in rows:
        status = _safe_text(item.get("status"))
        if status in counts:
            counts[status] += 1
        if item.get("clickable") == "yes" or item.get("api_action") or item.get("webui_section_id"):
            clickable += 1
        if item.get("api_action"):
            with_report += 1
        if item.get("webui_section_id"):
            with_open += 1
    return {
        "schema": "mms.setup_web.tui_mapping_summary.v1",
        "total": len(rows),
        "counts": counts,
        "clickable_rows": clickable,
        "rows_with_report_or_gate": with_report,
        "rows_with_open_target": with_open,
        "user_check_policy": "每行都可在 WebUI 点击：打开跳到页面落点，报告/人工确认验证 API 或人工确认卡，原生/草稿行再用保存预览核对写入。",
        "source_files": [
            "mms_display/tui.py:_connect_actions",
            "mms_display/tui.py:select_submodel_tui",
            "mms_display/tui.py:_settings_menu",
            "mms_core.py settings/provider/account/rescue action handlers",
        ],
        "policy": "原生/报告行由对应 WebUI 模块承接；TUI Settings 顶层只保留 WebUI、服务器/救援、语言、关于/升级；human_gate/missing 行保留 CLI 人工路径。load_balance 已明确移除。",
    }
