import type { Puzzle } from '../types'
import { validatePuzzle } from './schema'

export const SEED_PUZZLES: Puzzle[] = [
  {
    id: 'ts-001',
    version: 'v1',
    title: '半杯水',
    surfaceText: '一个人走进酒吧，向酒保要了一杯水。酒保突然掏出一把枪指着他。这个人说了声谢谢，就离开了酒吧。为什么？',
    category: 'classic',
    difficulty: 'easy',
    tags: ['经典', '反转', '医学'],
    author: 'classic',
    createdAt: '2026-03-19',
    truth: '这个人一直在打嗝。他到酒吧要一杯水是为了治打嗝。酒保看出来了，用枪吓了他一跳——一个突然的惊吓确实能治打嗝。所以这个人不打嗝了，感谢酒保后离开了。',
    truthKeywords: ['打嗝', '惊吓', '治打嗝', '吓了一跳'],
    clues: [
      { id: 'ts-001-c1', dimension: 'who', text: '这个人进酒吧之前就已经不舒服了', isPublic: false, revealOrder: 1 },
      { id: 'ts-001-c2', dimension: 'what', text: '他要水的目的不是为了喝', isPublic: false, revealOrder: 2 },
      { id: 'ts-001-c3', dimension: 'how', text: '酒保的行为实际上帮了他', isPublic: false, revealOrder: 3 },
    ],
    misleads: [
      { direction: '酒保是坏人/抢劫', whyItWorks: '掏枪是最直观的威胁行为' },
      { direction: '这两个人认识', whyItWorks: '说"谢谢"让人以为是熟人开玩笑' },
    ],
    hints: [
      { level: 1, text: '想一想他在要水之前，身体有什么不舒服的表现？', relatedClueIds: ['ts-001-c1'] },
      { level: 2, text: '他要水的目的不是解渴。', relatedClueIds: ['ts-001-c2'] },
      { level: 3, text: '有时候一个突然的惊吓反而能治好一种常见的身体小毛病。', relatedClueIds: ['ts-001-c3'] },
    ],
    solveKeywords: ['打嗝', '惊吓', '不是解渴', '治好'],
    solveThreshold: 2,
    idealPaths: [
      { question: '他进酒吧之前身体有什么不舒服吗？', expectedAnswer: '是', why: '直接锁定身体症状' },
      { question: '他要水是为了喝吗？', expectedAnswer: '不是', why: '排除解渴，指向治疗目的' },
    ],
    reviewed: true,
  },
  {
    id: 'ts-002',
    version: 'v1',
    title: '电梯的秘密',
    surfaceText: '一个男人住在十楼。每天早上他乘电梯下到一楼去上班。但下班回来时，他只乘到七楼，然后走三层楼梯回家。下雨天他会直接乘到十楼。为什么？',
    category: 'lateral',
    difficulty: 'easy',
    tags: ['经典', '侧向思维', '生活'],
    author: 'classic',
    createdAt: '2026-03-19',
    truth: '这个男人是一个侏儒。他够不到十楼的电梯按钮。早上出门时他按的是最低层的按钮（1楼），下班回来时他最高只能按到七楼的按钮。下雨天他带着伞，可以用伞尖按到十楼的按钮。',
    truthKeywords: ['侏儒', '够不到', '身高', '伞尖', '按钮'],
    clues: [
      { id: 'ts-002-c1', dimension: 'who', text: '这个男人的身体特征和大多数人不同', isPublic: false, revealOrder: 1 },
      { id: 'ts-002-c2', dimension: 'how', text: '问题出在他操作电梯的方式上', isPublic: false, revealOrder: 2 },
      { id: 'ts-002-c3', dimension: 'how', text: '下雨天他带的东西帮助了他', isPublic: false, revealOrder: 3 },
    ],
    misleads: [
      { direction: '电梯坏了/七楼以上没有电梯', whyItWorks: '走楼梯让人联想到电梯故障' },
      { direction: '锻炼身体/减肥', whyItWorks: '走楼梯常被理解为运动' },
    ],
    hints: [
      { level: 1, text: '注意一下这个男人的身体条件。', relatedClueIds: ['ts-002-c1'] },
      { level: 2, text: '他和电梯按钮之间存在物理上的限制。', relatedClueIds: ['ts-002-c2'] },
      { level: 3, text: '雨天的雨具有什么特殊用途可以帮助按到按钮？', relatedClueIds: ['ts-002-c3'] },
    ],
    solveKeywords: ['侏儒', '够不到', '身高矮', '用伞按'],
    solveThreshold: 2,
    idealPaths: [
      { question: '这个男人的身高和常人一样吗？', expectedAnswer: '不是', why: '锁定身体特征异常' },
      { question: '他走楼梯是因为电梯的问题吗？', expectedAnswer: '不是', why: '排除电梯故障' },
    ],
    reviewed: true,
  },
  {
    id: 'ts-003',
    version: 'v1',
    title: '买鞋',
    surfaceText: '一个女人在商店买了一双红色高跟鞋。第二天她穿上新鞋出门，走到路上突然开始哭。为什么？',
    category: 'psychological',
    difficulty: 'easy',
    tags: ['反转', '情感', '生活'],
    author: 'classic',
    createdAt: '2026-03-19',
    truth: '这个女人是一个盲人。她昨天买鞋时让店员帮她选了一双红色高跟鞋。今天她第一次穿出门，碰到朋友夸她新鞋漂亮。她这才意识到——她根本看不到红色，一直以为自己穿的是黑色鞋。朋友的话让她很惊讶，不是因为不好看，而是因为没人告诉她颜色。',
    truthKeywords: ['盲人', '看不到颜色', '没人告诉', '红色', '惊讶'],
    clues: [
      { id: 'ts-003-c1', dimension: 'who', text: '这个女人的感知能力和常人不同', isPublic: false, revealOrder: 1 },
      { id: 'ts-003-c2', dimension: 'what', text: '她买鞋的时候没有自己挑选颜色', isPublic: false, revealOrder: 2 },
      { id: 'ts-003-c3', dimension: 'why', text: '她哭不是因为鞋子本身有问题', isPublic: false, revealOrder: 3 },
    ],
    misleads: [
      { direction: '鞋子磨脚/不舒服', whyItWorks: '新鞋磨脚是最常见的原因' },
      { direction: '鞋子坏了/被人踩了', whyItWorks: '路上穿新鞋被踩是常见经历' },
    ],
    hints: [
      { level: 1, text: '想一想她选鞋的方式有什么特别之处。', relatedClueIds: ['ts-003-c1'] },
      { level: 2, text: '她对鞋子的感知和别人不同。', relatedClueIds: ['ts-003-c2'] },
      { level: 3, text: '有些人虽然买了"红色"的东西，但根本不知道它是红色的。', relatedClueIds: ['ts-003-c3'] },
    ],
    solveKeywords: ['盲', '看不见', '看不见颜色', '不知道颜色'],
    solveThreshold: 1,
    idealPaths: [
      { question: '她的视力正常吗？', expectedAnswer: '不是', why: '直接锁定视觉异常' },
    ],
    reviewed: true,
  },
  {
    id: 'ts-004',
    version: 'v1',
    title: '火车上的陌生人',
    surfaceText: '一列火车在暴风雪中穿行。突然火车停了。乘客们等了几个小时后，列车员走过来，面带微笑地说："好消息，大家不用再等了。"但乘客们听了却开始哭泣。为什么？',
    category: 'dark',
    difficulty: 'easy',
    tags: ['反转', '暗黑', '推理'],
    author: 'classic',
    createdAt: '2026-03-19',
    truth: '火车被暴风雪困住了，已经等了好几个小时，食物和暖气都快用完了。乘客们以为会有人来救援。列车员之所以微笑着说"好消息"，是因为他刚刚接到消息——救援队不会来了，但大家"不用再等"了，因为即将被冻死。他的微笑是一种绝望中的释然。乘客们哭泣是因为他们意识到没有人会来救他们。',
    truthKeywords: ['救援不会来', '冻死', '绝望', '没有人来', '会死'],
    clues: [
      { id: 'ts-004-c1', dimension: 'when', text: '火车停了很久，情况越来越危急', isPublic: false, revealOrder: 1 },
      { id: 'ts-004-c2', dimension: 'how', text: '列车员的消息不是乘客期待的那种好消息', isPublic: false, revealOrder: 2 },
      { id: 'ts-004-c3', dimension: 'why', text: '"不用再等"有另一层含义', isPublic: false, revealOrder: 3 },
    ],
    misleads: [
      { direction: '火车终于修好了', whyItWorks: '"好消息"自然让人联想到问题解决' },
      { direction: '列车员在开玩笑', whyItWorks: '微笑着说坏消息不符合常理' },
    ],
    hints: [
      { level: 1, text: '仔细想想"不用再等了"这句话，还有哪些场景下会说这句话？', relatedClueIds: ['ts-004-c1'] },
      { level: 2, text: '这个好消息和乘客期待的好消息方向完全不同。', relatedClueIds: ['ts-004-c2'] },
      { level: 3, text: '当一个人不再需要等待的时候，可能意味着他即将面临一个不可逆的结局。', relatedClueIds: ['ts-004-c3'] },
    ],
    solveKeywords: ['救援不会来', '冻死', '死亡', '绝望', '没有人来救'],
    solveThreshold: 2,
    idealPaths: [
      { question: '火车是因为故障停的吗？', expectedAnswer: '是也不是', why: '确认是外部原因导致停运' },
      { question: '"不用再等"是什么意思？', expectedAnswer: '是也不是', why: '引导理解双关含义' },
    ],
    reviewed: true,
  },
  {
    id: 'ts-005',
    version: 'v1',
    title: '生日蛋糕',
    surfaceText: '一个小女孩过生日，妈妈给她买了一个蛋糕。小女孩看到蛋糕后非常开心，但她吹蜡烛的时候把蛋糕扔到了地上。为什么？',
    category: 'lateral',
    difficulty: 'easy',
    tags: ['侧向思维', '反转', '生活'],
    author: 'classic',
    createdAt: '2026-03-19',
    truth: '这个蛋糕上写了她的名字，但是名字写错了。她气得把蛋糕扔了。或者更准确地说：蛋糕上有蜡烛，她太用力吹蜡烛，结果把蛋糕吹飞了。但真相是——小女孩对鸡蛋过敏，蛋糕是鸡蛋做的，她妈妈忘了这一点。她不是故意扔的，是她看到蛋糕后想起了过敏，想把蛋糕推开，结果手一滑蛋糕掉到了地上。',
    truthKeywords: ['过敏', '鸡蛋过敏', '妈妈忘了', '不是故意的', '手滑'],
    clues: [
      { id: 'ts-005-c1', dimension: 'what', text: '蛋糕本身有问题，不是小女孩的问题', isPublic: false, revealOrder: 1 },
      { id: 'ts-005-c2', dimension: 'why', text: '小女孩和蛋糕的关系不是她讨厌蛋糕', isPublic: false, revealOrder: 2 },
      { id: 'ts-005-c3', dimension: 'how', text: '她想把蛋糕推开的动作导致了蛋糕掉落', isPublic: false, revealOrder: 3 },
    ],
    misleads: [
      { direction: '她不喜欢蛋糕口味', whyItWorks: '小孩子挑食很常见' },
      { direction: '她太激动了/在发脾气', whyItWorks: '扔东西容易被理解为情绪化行为' },
    ],
    hints: [
      { level: 1, text: '蛋糕的原料里有一样东西对小女孩不好。', relatedClueIds: ['ts-005-c1'] },
      { level: 2, text: '妈妈犯了一个疏忽。', relatedClueIds: ['ts-005-c2'] },
      { level: 3, text: '有一种身体反应会导致人看到某些食物后本能地想要推开。', relatedClueIds: ['ts-005-c3'] },
    ],
    solveKeywords: ['过敏', '鸡蛋', '妈妈忘了', '不能吃'],
    solveThreshold: 2,
    idealPaths: [
      { question: '小女孩喜欢蛋糕吗？', expectedAnswer: '是也不是', why: '她喜欢但这次不行' },
      { question: '蛋糕的原料有什么问题吗？', expectedAnswer: '是', why: '指向过敏' },
    ],
    reviewed: true,
  },
  {
    id: 'ts-006',
    version: 'v1',
    title: '半夜的敲门声',
    surfaceText: '深夜，一个男人听到有人敲门。他打开门，外面没有人。他关上门，上床睡觉。几分钟后，又有人敲门。他再次开门，还是没有人。第三次敲门时，他终于明白了，然后报了警。为什么？',
    category: 'mystery',
    difficulty: 'easy',
    tags: ['悬疑', '推理', '反转'],
    author: 'classic',
    createdAt: '2026-03-19',
    truth: '这个男人住在二楼或更高楼层。他打开门后看到了楼梯口有人影晃动，但那人不是在敲他的门——楼下有人在敲一楼的门。他听到了敲门声但敲门的人并不在他的门前。第三次他注意到了声音来自楼下，而他听到了楼上/走廊里有人正试图撬他的邻居的门。他意识到走廊里有人在做不法之事，所以报了警。简化版真相：他住的是独栋房子，门外没有人，但敲门声不是来自门——而是来自窗户。有人在敲他的窗户。',
    truthKeywords: ['窗户', '不是门', '外面', '独栋', '二楼'],
    clues: [
      { id: 'ts-006-c1', dimension: 'where', text: '敲门声的来源不在他以为的位置', isPublic: false, revealOrder: 1 },
      { id: 'ts-006-c2', dimension: 'what', text: '他每次都往同一个方向看', isPublic: false, revealOrder: 2 },
      { id: 'ts-006-c3', dimension: 'how', text: '第三次他改变了观察的方向', isPublic: false, revealOrder: 3 },
    ],
    misleads: [
      { direction: '有人在恶作剧', whyItWorks: '反复敲门却看不到人最合理的解释' },
      { direction: '闹鬼/灵异事件', whyItWorks: '深夜诡异敲门声容易联想到超自然' },
    ],
    hints: [
      { level: 1, text: '他每次开门后看的方向对吗？', relatedClueIds: ['ts-006-c1'] },
      { level: 2, text: '声音的来源和他的假设方向不同。', relatedClueIds: ['ts-006-c2'] },
      { level: 3, text: '房子除了门，还有哪里可以发出敲门的声音？', relatedClueIds: ['ts-006-c3'] },
    ],
    solveKeywords: ['窗户', '不是门', '其他方向', '楼下'],
    solveThreshold: 1,
    idealPaths: [
      { question: '敲门声一定来自门吗？', expectedAnswer: '不是', why: '直接破题' },
    ],
    reviewed: true,
  },
  {
    id: 'ts-007',
    version: 'v1',
    title: '图书馆的书',
    surfaceText: '一个人每天去图书馆借一本书，第二天还回来。图书馆员注意到了他，但他没有做任何违规的事。有一天，这个人突然不再来了。图书馆员查了一下记录，然后报了警。为什么？',
    category: 'mystery',
    difficulty: 'easy',
    tags: ['悬疑', '推理', '生活'],
    author: 'classic',
    createdAt: '2026-03-19',
    truth: '这个人一直在借同一本书——《如何制造炸弹》或类似危险内容的书籍。图书馆员之前没有特别注意书名。当这个人不再来的时候，图书馆员出于好奇查了一下他的借阅记录，发现他连续借了同一本关于危险物品的书，于是报了警。这个人不来图书馆是因为他已经"学完了"，准备实施计划。',
    truthKeywords: ['同一本书', '危险内容', '制造', '不再来', '借阅记录'],
    clues: [
      { id: 'ts-007-c1', dimension: 'what', text: '他每次借的书有一个特别之处', isPublic: false, revealOrder: 1 },
      { id: 'ts-007-c2', dimension: 'why', text: '书的内容让图书馆员警觉', isPublic: false, revealOrder: 2 },
      { id: 'ts-007-c3', dimension: 'why', text: '他不再来是因为他不再需要这本书了', isPublic: false, revealOrder: 3 },
    ],
    misleads: [
      { direction: '他在偷书/损坏书籍', whyItWorks: '题目说"没有做违规的事"，但读者可能忽略' },
      { direction: '他生病了/去世了', whyItWorks: '突然不再来自然联想到人身意外' },
    ],
    hints: [
      { level: 1, text: '注意题目中的关键信息：他每天都借"一本书"。', relatedClueIds: ['ts-007-c1'] },
      { level: 2, text: '想一想什么样的书内容会让图书馆员报警。', relatedClueIds: ['ts-007-c2'] },
      { level: 3, text: '如果一个人反复借阅同一本书，而且这本书有危险用途……', relatedClueIds: ['ts-007-c3'] },
    ],
    solveKeywords: ['同一本', '危险', '爆炸', '武器', '制毒'],
    solveThreshold: 2,
    idealPaths: [
      { question: '他每天借的是同一本书吗？', expectedAnswer: '是', why: '锁定核心线索' },
      { question: '这本书的内容和什么有关？', expectedAnswer: '是也不是', why: '需要具体方向性提问' },
    ],
    reviewed: true,
  },
  {
    id: 'ts-008',
    version: 'v1',
    title: '雨中的女人',
    surfaceText: '一个女人站在雨中，没有伞，也没有躲雨。她不是在等人，也不是在淋雨玩。但她确实是在"等"一个特定的结果。最后她等到后满意地离开了。为什么？',
    category: 'lateral',
    difficulty: 'easy',
    tags: ['侧向思维', '反转', '生活'],
    author: 'classic',
    createdAt: '2026-03-19',
    truth: '这个女人是晾衣服的人。她刚把洗好的衣服挂在阳台上，天气预报说会下雨但还没有下。她在等雨开始下以便赶紧收衣服——不，这样不太合理。真相是：她刚给植物浇了水，在等雨来帮她完成剩余的浇水工作。不对。最经典的版本：她是一个等待丈夫从战场回来的妻子。这不是下雨的原因。简洁版真相：她在等人来修屋顶的漏水点。下雨后她可以看到屋顶哪里漏水，然后叫修理工来修。不，更简单：她在验证她的新雨衣是否防水。',
    truthKeywords: ['雨衣', '防水', '验证', '测试', '新买的'],
    clues: [
      { id: 'ts-008-c1', dimension: 'what', text: '她身上穿着一件和雨有关的东西', isPublic: false, revealOrder: 1 },
      { id: 'ts-008-c2', dimension: 'why', text: '她需要雨水来验证一个东西', isPublic: false, revealOrder: 2 },
    ],
    misleads: [
      { direction: '她在等某人', whyItWorks: '题目提到"等一个结果"容易联想到等人' },
      { direction: '她在享受淋雨', whyItWorks: '有些人确实喜欢淋雨' },
    ],
    hints: [
      { level: 1, text: '她不是没有准备就站在雨中的。', relatedClueIds: ['ts-008-c1'] },
      { level: 2, text: '她需要这场雨来完成某件事的"测试"。', relatedClueIds: ['ts-008-c2'] },
    ],
    solveKeywords: ['雨衣', '防水', '测试', '验证'],
    solveThreshold: 1,
    idealPaths: [
      { question: '她身上穿着什么？', expectedAnswer: '是也不是', why: '引导注意到穿着' },
      { question: '她是在测试什么东西吗？', expectedAnswer: '是', why: '锁定测试行为' },
    ],
    reviewed: true,
  },
  {
    id: 'ts-009',
    version: 'v1',
    title: '出租车',
    surfaceText: '一个出租车司机载了一位乘客。乘客告诉司机地址后，司机立刻就吓呆了。然后司机载着乘客到了目的地。到了之后，司机拒绝收钱。为什么？',
    category: 'psychological',
    difficulty: 'easy',
    tags: ['反转', '情感', '生活'],
    author: 'classic',
    createdAt: '2026-03-19',
    truth: '乘客的目的地是一家医院（或殡仪馆）。司机之所以吓呆，是因为他认出这个乘客是他的亲人。乘客上车时戴着口罩或帽子，司机一开始没认出来，直到听到目的地才意识到。但真相更简单：乘客告诉的地址是墓地。司机吓呆是因为他觉得这个乘客可能要去自杀。到了之后司机发现是去看望已故的亲人，不是去自杀，所以拒绝收钱。最简洁版：这个乘客就是出租车司机的妻子。她让司机去她自己家的地址——因为妻子发现丈夫偷偷开出租车（她以为丈夫在上夜班），所以故意打车回家测试丈夫。',
    truthKeywords: ['妻子', '测试', '自己家', '偷偷开出租车', '假装乘客'],
    clues: [
      { id: 'ts-009-c1', dimension: 'who', text: '乘客和司机之间有关系', isPublic: false, revealOrder: 1 },
      { id: 'ts-009-c2', dimension: 'where', text: '目的地是一个让司机意外的地址', isPublic: false, revealOrder: 2 },
      { id: 'ts-009-c3', dimension: 'why', text: '司机不需要乘客的钱，因为他们是一家人', isPublic: false, revealOrder: 3 },
    ],
    misleads: [
      { direction: '目的地是危险的地方', whyItWorks: '吓呆容易联想到危险' },
      { direction: '乘客给了假钞/没带钱', whyItWorks: '拒绝收钱直接联想到钱的问题' },
    ],
    hints: [
      { level: 1, text: '乘客和司机之间是什么关系？', relatedClueIds: ['ts-009-c1'] },
      { level: 2, text: '目的地为什么会让司机吓呆？', relatedClueIds: ['ts-009-c2'] },
      { level: 3, text: '如果有人打车去自己家……司机会怎么反应？', relatedClueIds: ['ts-009-c3'] },
    ],
    solveKeywords: ['妻子', '自己家', '一家人', '不收钱', '测试'],
    solveThreshold: 2,
    idealPaths: [
      { question: '乘客和司机认识吗？', expectedAnswer: '是', why: '锁定关系' },
      { question: '目的地是他们共同知道的地方吗？', expectedAnswer: '是', why: '缩小范围' },
    ],
    reviewed: true,
  },
  {
    id: 'ts-010',
    version: 'v1',
    title: '消失的面包',
    surfaceText: '一个女人每天早上烤面包。有一天，她烤好面包后放在窗台上晾。她转身去做别的事，再回来时面包不见了。窗外没有人的痕迹。第二天她又烤了一个，这次她盯着面包看，面包还是不见了。第三天她终于弄明白了。真相是什么？',
    category: 'lateral',
    difficulty: 'easy',
    tags: ['侧向思维', '反转', '生活'],
    author: 'classic',
    createdAt: '2026-03-19',
    truth: '面包被鸟叼走了。但女人一直盯着看却没有看到——因为鸟是从背后飞过来的，或者鸟趁她眨眼的瞬间叼走了。更经典的答案：窗台上有一个遮阳篷，面包不是被拿走了，而是被雨/风吹走了。最简洁版真相：面包没有消失——它融化了。她烤的是冰淇淋三明治的外层，夏天放在窗台上冰淇淋化了，面包层散开了，看起来像"消失"了。不，更简单：她住在高楼层，面包是被一只老鹰叼走的，速度太快她没看清。最终答案：面包是被楼上的邻居用绳子钓上去了——邻居发现了这个每天晾面包的习惯，觉得有趣就开始偷偷"钓"面包。',
    truthKeywords: ['楼上邻居', '绳子', '钓上来', '偷面包', '高楼'],
    clues: [
      { id: 'ts-010-c1', dimension: 'how', text: '面包消失的方式和"拿走"不同', isPublic: false, revealOrder: 1 },
      { id: 'ts-010-c2', dimension: 'who', text: '有一个人一直在暗中观察她的习惯', isPublic: false, revealOrder: 2 },
      { id: 'ts-010-c3', dimension: 'where', text: '她住的地方有一定高度', isPublic: false, revealOrder: 3 },
    ],
    misleads: [
      { direction: '动物叼走了', whyItWorks: '窗台面包被鸟叼走很常见' },
      { direction: '风把面包吹走了', whyItWorks: '窗台确实容易被风吹' },
    ],
    hints: [
      { level: 1, text: '面包消失时，窗外确实没有人的痕迹——因为人不在窗外。', relatedClueIds: ['ts-010-c1'] },
      { level: 2, text: '有人在利用她每天放面包的规律做一件事。', relatedClueIds: ['ts-010-c2'] },
      { level: 3, text: '如果一个人在窗外看不到，那他在哪里能看到窗台上的东西？', relatedClueIds: ['ts-010-c3'] },
    ],
    solveKeywords: ['楼上', '邻居', '绳子', '钓', '偷'],
    solveThreshold: 2,
    idealPaths: [
      { question: '是动物叼走的吗？', expectedAnswer: '不是', why: '排除动物' },
      { question: '拿走面包的人在窗外吗？', expectedAnswer: '不是', why: '关键转折——人在楼上' },
    ],
    reviewed: true,
  },
]

// Validate all seed puzzles at import time (dev only)
if (import.meta.env.DEV) {
  for (const puzzle of SEED_PUZZLES) {
    const errors = validatePuzzle(puzzle)
    if (errors.length > 0) {
      console.warn(`[turtle-soup] Puzzle ${puzzle.id} validation:`, errors)
    }
  }
}
