"""Launcher-adjacent command handlers with dependencies injected by core."""

from __future__ import annotations

import argparse
import os
import shlex
import sys


def _text(value, text_cls):
    if callable(text_cls):
        return text_cls(value)
    try:
        from rich.text import Text
        return Text(value)
    except ImportError:
        return str(value).replace("[", "\\[").replace("]", "\\]")


def handle_session_command(
    argv,
    *,
    command_name,
    handle_session_ls,
    handle_session_info,
    handle_session_prune,
):
    parser = argparse.ArgumentParser(
        prog=f"{command_name} session",
        description="查看 MMS 托管 CLI session",
    )
    subparsers = parser.add_subparsers(dest="subcommand")

    ls_parser = subparsers.add_parser("ls", help="列出已索引 session")
    ls_parser.add_argument("--cli", default="claude", choices=["claude"])

    info_parser = subparsers.add_parser("info", help="查看单个 session 详情")
    info_parser.add_argument("session_id", help="session_id 或 pid-<pid>")
    info_parser.add_argument("--cli", default="claude", choices=["claude"])

    prune_parser = subparsers.add_parser("prune", help="列出或删除 stale MMS gateway session")
    prune_parser.add_argument("--cli", default="all", choices=["claude", "codex", "opencode", "all"])
    prune_parser.add_argument("--dry-run", action="store_true", help="只列出候选项；默认行为")
    prune_parser.add_argument("--apply", action="store_true", help="实际删除 stale session；默认只 dry-run")
    prune_parser.add_argument("--yes", action="store_true", help="配合 --apply，确认删除")

    args = parser.parse_args(argv)
    if args.subcommand == "ls":
        handle_session_ls(args.cli)
        return
    if args.subcommand == "info":
        handle_session_info(args.session_id, args.cli)
        return
    if args.subcommand == "prune":
        handle_session_prune(args.cli, apply=bool(args.apply), yes=bool(args.yes))
        return
    parser.print_help()


def handle_env_command(
    cfg,
    argv,
    *,
    command_name,
    resolve_named_preset,
    resolve_preset_export_runtime,
    env_dir,
    preset_env_file_path,
    display_title,
    console,
):
    parser = argparse.ArgumentParser(
        prog=f"{command_name} env",
        description="输出预设对应的 export 环境变量",
    )
    parser.add_argument("preset_name", help="预设名称")
    parser.add_argument("--apply", action="store_true", help="写入 ~/.config/mms/env/<preset>.sh")
    parser.add_argument("--provider", help="临时覆盖预设中的 provider")
    args = parser.parse_args(argv)

    preset = resolve_named_preset(cfg, args.preset_name)
    if preset is None:
        return

    result = resolve_preset_export_runtime(cfg, preset, provider_override=args.provider)
    if result is None:
        return

    cli, exports, _runtime = result
    lines = [f"export {key}={shlex.quote(str(value))}" for key, value in exports.items()]
    export_block = "\n".join(lines)

    console.print(f"\n[bold cyan]{args.preset_name} ({cli}) 环境变量:[/bold cyan]\n")
    console.print(export_block)

    if args.apply:
        os.makedirs(env_dir, exist_ok=True)
        env_path = preset_env_file_path(args.preset_name)
        with open(env_path, "w") as handle:
            handle.write(f"# Generated by {display_title()} — preset: {args.preset_name}\n")
            handle.write(export_block + "\n")
        console.print(f"\n[green]✓ 已写入 {env_path}[/green]")
        console.print(f"[dim]需要时手动执行: source {env_path}[/dim]")
    else:
        console.print(
            f"\n[dim]复制上面的命令临时使用，或执行 {command_name} env {args.preset_name} --apply 生成独立 env 文件[/dim]"
        )


def handle_activate_command(
    cfg,
    argv,
    *,
    command_name,
    resolve_named_preset,
    resolve_preset_export_runtime,
):
    parser = argparse.ArgumentParser(
        prog=f"{command_name} activate",
        description="输出可 eval 的 export 语句",
    )
    parser.add_argument("preset_name", help="预设名称")
    parser.add_argument("--provider", help="临时覆盖预设中的 provider")
    args = parser.parse_args(argv)

    preset = resolve_named_preset(cfg, args.preset_name, stderr_only=True)
    if preset is None:
        sys.exit(1)

    result = resolve_preset_export_runtime(cfg, preset, provider_override=args.provider, stderr_only=True)
    if result is None:
        sys.exit(1)

    _cli, exports, _runtime = result
    for key, value in exports.items():
        print(f"export {key}={shlex.quote(str(value))}")

    if sys.stderr.isatty():
        print(f"# ✓ preset '{args.preset_name}' activated", file=sys.stderr)


def handle_models_command(
    cfg,
    argv,
    *,
    command_name,
    provider_map,
    select_provider_for_models,
    manage_provider_models,
    text_cls,
    console,
):
    if argv and argv[0] in {"-h", "--help"}:
        console.print("[cyan]用法:[/cyan]", _text(f"{command_name} ls [provider_id]", text_cls))
        console.print("[dim]不带参数时先选通道，再进入模型列表与测速页。[/dim]")
        return
    provider_id = str(argv[0]).strip() if argv else ""
    providers = provider_map(cfg)
    if provider_id:
        if provider_id not in providers:
            console.print(f"[red]未找到模型源: {provider_id}[/red]")
            console.print(f"[dim]可用模型源: {', '.join(sorted(providers.keys()))}[/dim]")
            sys.exit(1)
    else:
        provider_id = select_provider_for_models(cfg)
        if not provider_id:
            return

    manage_provider_models(cfg, provider_id)


def select_provider_for_models(
    cfg,
    *,
    list_manage_targets,
    table_cls,
    prompt_cls,
    console,
):
    providers = [item for item in list_manage_targets(cfg) if item.get("kind") == "provider"]
    if not providers:
        console.print("[yellow]当前还没有可管理的网关通道[/yellow]")
        return None

    table = table_cls(title="模型与测速 · 选择通道", show_lines=True)
    table.add_column("#", style="cyan", width=4)
    table.add_column("显示名", style="yellow")
    table.add_column("内部标识", style="green")
    table.add_column("默认", style="magenta", width=6)
    table.add_column("状态", style="white")
    for index, provider in enumerate(providers, 1):
        table.add_row(
            str(index),
            provider.get("title", ""),
            provider.get("id", ""),
            provider.get("default_label", ""),
            provider.get("status", ""),
        )
    console.print(table)

    while True:
        raw = prompt_cls.ask("选择要查看的通道，直接回车返回", default="")
        if not raw:
            return None
        if raw.isdigit():
            idx = int(raw)
            if 1 <= idx <= len(providers):
                return providers[idx - 1]["id"]
        console.print(f"[red]请输入 1-{len(providers)} 的编号[/red]")


def pick_manual_models(models, *, table_cls, prompt_cls, console):
    if not models:
        return []
    table = table_cls(title="选择要预热的模型", show_lines=True)
    table.add_column("#", style="cyan", width=4)
    table.add_column("模型", style="green")
    for idx, model_name in enumerate(models, 1):
        table.add_row(str(idx), model_name)
    console.print(table)
    raw = prompt_cls.ask("输入模型编号，支持逗号分隔；直接回车取消", default="")
    if not raw.strip():
        return []
    selected = []
    seen = set()
    for chunk in raw.split(","):
        value = chunk.strip()
        if not value.isdigit():
            continue
        idx = int(value)
        if 1 <= idx <= len(models):
            model_name = models[idx - 1]
            if model_name not in seen:
                seen.add(model_name)
                selected.append(model_name)
    return selected


def warm_model_request(
    provider,
    model_name,
    *,
    ensure_httpx,
    get_httpx,
    resolve_anthropic_base_url,
    runtime_httpx_request,
    provider_openai_base_url,
):
    model_name = str(model_name or "").strip()
    if not model_name:
        return False, "empty model"
    ensure_httpx()
    if get_httpx() is None:
        return False, "缺少 httpx"

    protocols = provider.get("protocols", [])
    api_key = provider.get("api_key", "")
    openai_api_key = provider.get("openai_api_key") or api_key
    timeout = 30
    if not api_key and not openai_api_key:
        return False, "缺少 API Key"

    use_anthropic = "anthropic_messages" in protocols and "claude" in model_name.lower()
    try:
        if use_anthropic:
            base_url, _method = resolve_anthropic_base_url(provider, probe_model=model_name)
            if not base_url:
                return False, "无法解析 Anthropic 地址"
            response = runtime_httpx_request(
                "POST",
                f"{base_url.rstrip('/')}/v1/messages",
                runtime=provider,
                headers={
                    "x-api-key": api_key,
                    "anthropic-version": "2023-06-01",
                    "Content-Type": "application/json",
                },
                json={
                    "model": model_name,
                    "max_tokens": 1,
                    "messages": [{"role": "user", "content": "warmup"}],
                },
                timeout=timeout,
            )
        else:
            base_url = provider_openai_base_url(provider)
            if not base_url:
                return False, "缺少 OpenAI 地址"
            response = runtime_httpx_request(
                "POST",
                f"{base_url.rstrip('/')}/chat/completions",
                runtime=provider,
                headers={
                    "Authorization": f"Bearer {openai_api_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": model_name,
                    "messages": [{"role": "user", "content": "warmup"}],
                    "max_tokens": 1,
                    "temperature": 0,
                    "stream": False,
                },
                timeout=timeout,
            )
        if response.status_code >= 400:
            detail = response.text.strip().replace("\n", " ")
            if len(detail) > 120:
                detail = detail[:117] + "..."
            return False, f"HTTP {response.status_code}: {detail or 'request failed'}"
        return True, "ok"
    except Exception as exc:
        return False, str(exc)


def handle_warm_command(
    cfg,
    argv,
    *,
    command_name,
    provider_map,
    select_provider_for_warm,
    resolve_provider_context,
    probe_models,
    recent_models_for_provider,
    pick_manual_models,
    warm_model_request,
    text_cls,
    panel_cls,
    prompt_cls,
    confirm_cls,
    table_cls,
    console,
):
    if argv and argv[0] in {"-h", "--help"}:
        console.print("[cyan]用法:[/cyan]", _text(f"{command_name} warm [provider_id]", text_cls))
        console.print("[dim]不带参数时先选通道，再选择最近使用 / 手动选择 / 全部模型。[/dim]")
        return

    provider_id = str(argv[0]).strip() if argv else ""
    providers = provider_map(cfg)
    if provider_id:
        if provider_id not in providers:
            console.print(f"[red]未找到模型源: {provider_id}[/red]")
            console.print(f"[dim]可用模型源: {', '.join(sorted(providers.keys()))}[/dim]")
            sys.exit(1)
    else:
        provider_id = select_provider_for_warm(cfg)
        if not provider_id:
            return

    provider = resolve_provider_context(cfg, provider_id)
    probe = probe_models(provider, emit_output=False)
    models = list(probe.get("models") or [])
    if not models:
        console.print("[yellow]当前通道没有可预热的模型[/yellow]")
        return

    recent_models = [item for item in recent_models_for_provider(provider_id) if item in models]

    console.print(panel_cls(
        f"[bold]通道:[/bold] {provider.get('name', provider_id)}\n"
        f"[bold]可用模型数:[/bold] {len(models)}\n"
        f"[dim]预热会真实发请求，建议优先预热最近常用模型，不建议默认全量预热。[/dim]",
        title="模型预热",
        border_style="cyan",
    ))
    console.print("  1. 预热最近使用模型（推荐）")
    console.print("  2. 手动选择模型")
    console.print("  3. 预热全部模型（不推荐）")
    console.print("  4. 返回")
    choice = prompt_cls.ask("选择操作", choices=["1", "2", "3", "4"], default="1")

    selected_models = []
    if choice == "1":
        selected_models = recent_models
        if not selected_models:
            console.print("[yellow]当前没有最近使用模型，已改为手动选择[/yellow]")
            selected_models = pick_manual_models(models)
    elif choice == "2":
        selected_models = pick_manual_models(models)
    elif choice == "3":
        if not confirm_cls.ask("确认预热当前通道全部模型？这会产生真实请求成本。", default=False):
            console.print("[yellow]已取消全量预热[/yellow]")
            return
        selected_models = models
    else:
        return

    if not selected_models:
        console.print("[yellow]没有选择任何模型，已取消预热[/yellow]")
        return

    results = []
    for model_name in selected_models:
        console.print(f"[dim]正在预热 {model_name} ...[/dim]")
        ok, detail = warm_model_request(provider, model_name)
        results.append((model_name, ok, detail))

    table = table_cls(title=f"{provider.get('name', provider_id)} · 预热结果", show_lines=True)
    table.add_column("模型", style="cyan")
    table.add_column("结果", style="green")
    table.add_column("详情", style="yellow")
    success_count = 0
    for model_name, ok, detail in results:
        if ok:
            success_count += 1
        table.add_row(model_name, "成功" if ok else "失败", detail)
    console.print(table)
    console.print(f"[green]✓ 已完成预热：成功 {success_count} / {len(results)}[/green]")


def handle_export(
    cli_name,
    provider,
    *,
    apply=False,
    cli_names,
    get_export_env,
    env_dir,
    env_file_path,
    display_title,
    export_command_hint,
    console,
):
    if cli_name not in cli_names:
        console.print(f"[red]不支持的 CLI: {cli_name}[/red]")
        console.print(f"支持: {', '.join(cli_names)}")
        return

    try:
        exports = get_export_env(cli_name, provider)
    except RuntimeError as exc:
        console.print(f"[red]{exc}[/red]")
        if cli_name == "pi":
            console.print("[dim]Pi 的 export 需要先确定 model；请改用带 model 的 preset/env，或在启动前先选定模型。[/dim]")
        return
    if not exports:
        console.print(f"[yellow]{cli_name} 无需 export；启动时会按 CLI 自己的参数或登录方式处理[/yellow]")
        return

    lines = [f"export {key}={shlex.quote(str(value))}" for key, value in exports.items()]
    export_block = "\n".join(lines)

    console.print(f"\n[bold cyan]{cli_name} 环境变量:[/bold cyan]\n")
    console.print(export_block)

    if apply:
        os.makedirs(env_dir, exist_ok=True)
        path = env_file_path(cli_name)
        with open(path, "w") as handle:
            handle.write(f"# Generated by {display_title()}\n")
            handle.write(export_block + "\n")

        console.print(f"\n[green]✓ 已写入 {path}[/green]")
        console.print("[dim]这是独立 env 文件，不会自动修改 ~/.zshrc 或 ~/.bashrc[/dim]")
        console.print(f"[dim]需要时手动执行: source {path}[/dim]")
    else:
        console.print(
            f"\n[dim]复制上面的命令临时使用，或执行 {export_command_hint(cli_name)} 生成独立 env 文件[/dim]"
        )


def emit_preset_error(message, *, stderr_only=False, console):
    if stderr_only:
        print(message, file=sys.stderr)
    else:
        console.print(message)


def preset_env_file_path(preset_name, *, env_dir):
    safe_name = "".join(
        ch if ch.isalnum() or ch in {"-", "_"} else "-"
        for ch in str(preset_name or "").strip().lower()
    ).strip("-_")
    safe_name = safe_name or "preset"
    return os.path.join(env_dir, f"{safe_name}.sh")


def resolve_named_preset(
    cfg,
    preset_name,
    *,
    normalize_preset_entry,
    emit_preset_error,
    stderr_only=False,
):
    presets = cfg.get("presets", {})
    if preset_name not in presets:
        emit_preset_error(f"预设 '{preset_name}' 不存在", stderr_only=stderr_only)
        if presets:
            emit_preset_error(f"可用预设: {', '.join(presets.keys())}", stderr_only=stderr_only)
        return None
    return normalize_preset_entry(preset_name, presets[preset_name])


def infer_preset_auth_mode(preset):
    if not isinstance(preset, dict):
        return None
    if preset.get("bridge"):
        return "oauth_bridge"
    if preset.get("account"):
        return "oauth"
    if preset.get("provider"):
        return "api_key"
    return None


def resolve_preset_export_runtime(
    cfg,
    preset,
    provider_override=None,
    *,
    stderr_only=False,
    infer_preset_auth_mode,
    emit_preset_error,
    ensure_provider_credentials,
    validate_provider_for_cli,
    get_export_env,
    preset_model_info=None,
):
    cli = preset.get("cli", "claude")
    auth_mode = infer_preset_auth_mode(preset)

    if auth_mode in ("oauth", "oauth_bridge"):
        emit_preset_error(f"此预设使用 {auth_mode} 模式，不支持 env export", stderr_only=stderr_only)
        return None

    provider_id = provider_override or preset.get("provider") or None

    runtime = ensure_provider_credentials(cfg, provider_id)
    if runtime is None:
        emit_preset_error(f"无法解析 provider: {provider_id or 'default'}", stderr_only=stderr_only)
        return None

    if not provider_id and sys.stderr.isatty():
        default_name = runtime.get("id", "default") if isinstance(runtime, dict) else "default"
        print(f"预设未指定 provider，使用默认: {default_name}", file=sys.stderr)

    try:
        validate_provider_for_cli(cli, runtime)
    except Exception as exc:
        emit_preset_error(str(exc), stderr_only=stderr_only)
        return None

    model_info = preset_model_info(preset) if callable(preset_model_info) else None
    try:
        if model_info:
            exports = get_export_env(cli, runtime, model_info=model_info)
        else:
            exports = get_export_env(cli, runtime)
    except TypeError as exc:
        if "model_info" not in str(exc):
            raise
        exports = get_export_env(cli, runtime)
    except RuntimeError as exc:
        emit_preset_error(str(exc), stderr_only=stderr_only)
        return None
    if not exports:
        emit_preset_error(f"{cli} 无需 export；启动时会按 CLI 自己的参数或登录方式处理", stderr_only=stderr_only)
        return None

    return cli, exports, runtime


def handle_presets_command(
    cfg,
    *,
    preset_has_visible_model_options,
    preset_cli_enabled=None,
    infer_preset_auth_mode,
    default_provider_id,
    table_cls,
    console,
):
    presets = cfg.get("presets", {})
    visible_presets = {
        name: preset for name, preset in presets.items()
        if preset_has_visible_model_options(preset)
        and (not callable(preset_cli_enabled) or preset_cli_enabled(preset))
    }
    if visible_presets:
        table = table_cls(title="已保存预设")
        table.add_column("名称", style="cyan")
        table.add_column("CLI", style="green")
        table.add_column("Provider", style="magenta")
        table.add_column("模型", style="yellow")
        table.add_column("描述", style="dim")
        table.add_column("模式", style="blue")
        for name, preset in visible_presets.items():
            model_str = preset.get("model", f"opus={preset.get('opus','')}, sonnet={preset.get('sonnet','')}")
            desc = preset.get("description", "")
            auth = infer_preset_auth_mode(preset) or "—"
            table.add_row(
                name,
                preset.get("cli", "?"),
                preset.get("provider", default_provider_id),
                str(model_str),
                desc,
                auth,
            )
        console.print(table)
