#!/usr/bin/env python3
"""Vendor the @ctrixin/pi-btw extension bundle into assets/pi-extensions/pi-btw/.

MMS injects one built file into every MMS-launched Pi session. This script is a
maintenance entry point a human or an agent runs deliberately; nothing in the
launch path calls it.

Sources (pick one):

  # local fork checkout, optionally pinned to a ref that HEAD must equal
  python3 scripts/sync_pi_btw.py --source ~/auto-skills/CtriXin-repo/pi-btw --ref v0.59.0-fork.1

  # an npm tarball that was already unpacked and had its dependencies installed
  python3 scripts/sync_pi_btw.py --tarball /tmp/ctrixin-pi-btw-0.59.0-fork.1/package

Checks without writing:

  python3 scripts/sync_pi_btw.py --check

The bundle keeps Pi's own packages external (Pi resolves them, and a second copy
inside our bundle would be a different module instance) and inlines everything
else, notably @narumitw/pi-tui-kit, because the vendored file has no
node_modules to resolve at. Every package that ends up inlined gets its license
copied into THIRD-PARTY-NOTICES.md next to the artifact.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
VENDOR_DIR = ROOT_DIR / "assets" / "pi-extensions" / "pi-btw"
BUNDLE_NAME = "index.ts"
VERSION_NAME = "VERSION"
SOURCE_NAME = "SOURCE.json"
NOTICES_NAME = "THIRD-PARTY-NOTICES.md"

# The fork was published under @ctrixin/pi-btw and renamed when that npm org
# turned out to be taken (D1 revised 2026-09-14): @ctrixin-dev/pi-btw. Accept
# either so a re-sync does not depend on which side of the rename the ref is on.
PACKAGE_NAMES = ("@ctrixin/pi-btw", "@ctrixin-dev/pi-btw")
PACKAGE_NAME = PACKAGE_NAMES[0]
UPSTREAM_PACKAGE = "@narumitw/pi-btw"
# Pi bundles these for extensions, so an extension must not ship its own copy.
# See pi docs/packages.md ("Dependencies").
PEER_PREFIX = "@earendil-works/"
PEER_ALLOWLIST = {"typebox"}
MAX_BUNDLE_BYTES = 4_000_000
MIN_BUNDLE_BYTES = 50_000

SPECIFIER_RE = re.compile(r"""\b(?:from|import)\s*\(?\s*["']([^"'\n]+?)["']""")
# `@narumitw/pi-tui-kit` loads its optional syntax highlighter through
# `createRequire(...)`, which esbuild cannot inline. Those specifiers stay
# unresolved in the vendored file, so the sync has to name them out loud.
LAZY_REQUIRE_RE = re.compile(r"""\brequire[A-Za-z0-9_]*\s*\(\s*["']([^"'\n]+?)["']""")
NODE_MODULES_RE = re.compile(r"(?:^|/)node_modules((?:/@[^/]+)?/[^/]+)")


class SyncError(RuntimeError):
    pass


def _run(command: list[str], **kwargs) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, capture_output=True, text=True, check=False, **kwargs)


def _banner(version: str, ref: str, package: str = PACKAGE_NAME) -> str:
    return "\n".join(
        (
            "// @generated by scripts/sync_pi_btw.py from "
            f"{package} {version} ({ref}); do not edit.",
            "// @ts-nocheck -- generated JavaScript uses a .ts extension for Pi's Jiti loader.",
        )
    )


def _package_manifest(source: Path) -> dict:
    manifest = source / "package.json"
    if not manifest.is_file():
        raise SyncError(f"no package.json under {source}")
    try:
        payload = json.loads(manifest.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SyncError(f"invalid {manifest}: {exc}") from exc
    if payload.get("name") not in PACKAGE_NAMES:
        raise SyncError(
            f"{source} is {payload.get('name')!r}, expected one of {', '.join(PACKAGE_NAMES)}"
        )
    if not str(payload.get("version") or "").strip():
        raise SyncError(f"{source}/package.json has no version")
    return payload


def _git(source: Path, *args: str) -> str:
    completed = _run(["git", "-C", str(source), *args])
    if completed.returncode != 0:
        raise SyncError(f"git {' '.join(args)} failed in {source}: {completed.stderr.strip()}")
    return completed.stdout.strip()


def _resolve_ref(source: Path, ref: str) -> tuple[str, str]:
    """Return (ref label, commit) and refuse a checkout that is not the ref."""
    head = _git(source, "rev-parse", "--verify", "HEAD^{commit}")
    if not ref:
        label = _git(source, "describe", "--tags", "--always", "--dirty") or head[:10]
        return label, head
    commit = _git(source, "rev-parse", "--verify", f"{ref}^{{commit}}")
    if commit != head:
        raise SyncError(
            f"{source} HEAD {head[:10]} != {ref} {commit[:10]}; check out the ref first"
        )
    # Only tracked content feeds the bundle; node_modules/ and dist/ are
    # untracked build input and output.
    if _git(source, "status", "--porcelain", "--untracked-files=no"):
        raise SyncError(f"{source} has uncommitted changes; refusing to vendor a dirty tree")
    return ref, commit


def _entry_point(source: Path) -> str:
    if (source / "src" / "index.ts").is_file():
        return "src/index.ts"
    if (source / "dist" / "index.ts").is_file():
        # An npm tarball without src/: dist/ is already a bundle that keeps Pi
        # packages plus @narumitw/pi-tui-kit external.
        return "dist/index.ts"
    raise SyncError(f"{source} has neither src/index.ts nor dist/index.ts")


def _esbuild_bin(source: Path) -> str:
    local = source / "node_modules" / ".bin" / "esbuild"
    if local.is_file() and os.access(local, os.X_OK):
        return str(local)
    which = shutil.which("esbuild")
    if which:
        return which
    raise SyncError(
        f"esbuild is neither in {source}/node_modules/.bin nor on PATH; "
        f"run `npm ci` in the {PACKAGE_NAME} checkout first"
    )


def build_bundle(source: Path, ref: str, version: str, package: str = PACKAGE_NAME) -> tuple[str, dict]:
    """Return (bundle text, esbuild metafile)."""
    esbuild = _esbuild_bin(source)
    with tempfile.TemporaryDirectory(prefix="pi-btw-vendor-") as tmp:
        out = Path(tmp) / "bundle.mjs"
        meta = Path(tmp) / "meta.json"
        completed = _run(
            [
                esbuild,
                _entry_point(source),
                "--bundle",
                "--format=esm",
                "--platform=node",
                "--target=es2022",
                "--log-level=warning",
                f"--banner:js={_banner(version, ref, package)}",
                f"--external:{PEER_PREFIX}*",
                "--external:typebox",
                f"--outfile={out}",
                f"--metafile={meta}",
            ],
            cwd=source,
        )
        if completed.returncode != 0 or completed.stderr.strip():
            raise SyncError(
                f"esbuild failed or reported warnings:\n{completed.stdout}{completed.stderr}"
            )
        return out.read_text(encoding="utf-8"), json.loads(meta.read_text(encoding="utf-8"))


def _import_specifiers(text: str) -> set[str]:
    """Every module the bundle imports, one line at a time.

    Scanning per line keeps the answer to real specifiers: a greedy `[^"']+`
    across the whole file would happily match the code between two unrelated
    string literals.
    """
    return _scan(text, (SPECIFIER_RE,))


def _lazy_requires(text: str) -> set[str]:
    return _scan(text, (LAZY_REQUIRE_RE,))


def _scan(text: str, patterns: tuple[re.Pattern[str], ...]) -> set[str]:
    found: set[str] = set()
    for line in text.splitlines():
        for pattern in patterns:
            for match in pattern.findall(line):
                if match.startswith((".", "/", "node:", "file:")):
                    continue
                found.add(match)
    return found


def bundled_packages(metafile: dict) -> set[str]:
    """Package names whose sources were actually inlined into the bundle."""
    found: set[str] = set()
    for input_path in (metafile.get("inputs") or {}):
        normalized = input_path.replace("\\", "/")
        match = NODE_MODULES_RE.search(normalized)
        if not match:
            continue
        name = match.group(1).lstrip("/")
        found.add(name)
    return {name for name in found if not name.startswith(PEER_PREFIX)}


def verify_bundle(text: str, metafile: dict) -> dict:
    """Guard what MMS is about to inject into every Pi session."""
    if not text.startswith("// @generated by scripts/sync_pi_btw.py"):
        raise SyncError("bundle is missing the generated banner")
    size = len(text.encode("utf-8"))
    if not MIN_BUNDLE_BYTES <= size <= MAX_BUNDLE_BYTES:
        raise SyncError(f"bundle size {size} is outside the expected range")
    for specifier in sorted(_import_specifiers(text)):
        if specifier.startswith(PEER_PREFIX) or specifier in PEER_ALLOWLIST:
            continue
        raise SyncError(f"bundle imports an unexpected module: {specifier}")
    lazy = [
        specifier
        for specifier in sorted(_lazy_requires(text))
        if not specifier.startswith(PEER_PREFIX) and specifier not in PEER_ALLOWLIST
    ]
    node = shutil.which("node")
    if not node:
        raise SyncError("node is required to syntax-check the bundle")
    with tempfile.NamedTemporaryFile("w", suffix=".mjs", delete=False, encoding="utf-8") as handle:
        probe = Path(handle.name)
        handle.write(text)
    try:
        checked = _run([node, "--check", str(probe)])
        if checked.returncode != 0:
            raise SyncError(f"node --check rejected the bundle:\n{checked.stderr.strip()}")
    finally:
        probe.unlink(missing_ok=True)
    return {
        "bytes": size,
        "externalPeers": sorted(_import_specifiers(text)),
        "bundledDependencies": sorted(bundled_packages(metafile)),
        "unresolvedRequires": lazy,
    }


def _third_party_notices(source: Path, packages: set[str], package: str = PACKAGE_NAME) -> str:
    lines = [
        "# Third-party code inside `index.ts`",
        "",
        f"`index.ts` is the esbuild output of `{package}` — a fork of",
        f"`{UPSTREAM_PACKAGE}` (see `NOTICE` for provenance and `LICENSE` for the",
        "MIT terms). Besides the fork itself it inlines these runtime",
        "dependencies, because the vendored file has no node_modules to resolve at:",
        "",
    ]
    for name in sorted(packages):
        package_dir = source / "node_modules" / name
        license_text = ""
        for candidate in ("LICENSE", "LICENSE.md", "LICENCE"):
            path = package_dir / candidate
            if path.is_file():
                license_text = path.read_text(encoding="utf-8", errors="replace").strip()
                break
        version = ""
        manifest = package_dir / "package.json"
        if manifest.is_file():
            try:
                version = str(json.loads(manifest.read_text(encoding="utf-8")).get("version") or "")
            except json.JSONDecodeError:
                version = ""
        lines.append(f"- `{name}`" + (f" {version}" if version else ""))
        if license_text:
            lines.append(f"  license: {license_text.splitlines()[0]}")
    lines += [
        "",
        "Full license texts are shipped in the source packages; see",
        "`SOURCE.json` for the exact ref and sha256 of what is vendored here.",
        "",
    ]
    return "\n".join(lines)


def _current_record() -> dict:
    record_path = VENDOR_DIR / SOURCE_NAME
    if not record_path.is_file():
        return {}
    try:
        return json.loads(record_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _pi_version() -> str:
    pi = shutil.which("pi")
    if not pi:
        return ""
    completed = _run([pi, "--version"])
    return completed.stdout.strip() if completed.returncode == 0 else ""


def verify_loads(path: Path) -> None:
    """Ask real Pi to load the file and report the commands it registered."""
    pi = shutil.which("pi")
    if not pi:
        raise SyncError("--verify asked for pi but it is not on PATH")
    with tempfile.TemporaryDirectory(prefix="pi-btw-load-") as tmp:
        env = dict(os.environ)
        env["PI_CODING_AGENT_DIR"] = tmp
        env["HOME"] = tmp
        try:
            completed = subprocess.run(
                [pi, "--mode", "rpc", "--no-session", "--extension", str(path)],
                input='{"type":"get_commands"}\n',
                capture_output=True,
                text=True,
                env=env,
                check=False,
                timeout=120,
            )
        except subprocess.TimeoutExpired:
            raise SyncError("pi did not answer get_commands within 120s") from None
    payload: dict = {}
    for line in completed.stdout.splitlines():
        try:
            candidate = json.loads(line)
        except json.JSONDecodeError:
            continue
        if candidate.get("type") == "response" and candidate.get("command") == "get_commands":
            payload = candidate
            break
    names = sorted(
        str(item.get("name") or "")
        for item in (payload.get("data") or {}).get("commands", [])
        if item.get("source") == "extension"
    )
    if "btw" not in names or "btw:cancel" not in names:
        raise SyncError(
            "pi did not register the fork command family: "
            f"{names or completed.stdout[:200]}{completed.stderr[:200]}"
        )
    print(f"[verify] pi {names}")


def _check() -> int:
    bundle = VENDOR_DIR / BUNDLE_NAME
    if not bundle.is_file():
        print(f"[check] FAIL missing {bundle.relative_to(ROOT_DIR)}", file=sys.stderr)
        return 1
    record = _current_record()
    if not record:
        print(f"[check] FAIL {SOURCE_NAME.relative_to(ROOT_DIR)} is missing", file=sys.stderr)
        return 1
    try:
        facts = verify_bundle(bundle.read_text(encoding="utf-8"), {"inputs": {}})
    except SyncError as exc:
        print(f"[check] FAIL {exc}", file=sys.stderr)
        return 1
    digest = hashlib.sha256(bundle.read_bytes()).hexdigest()
    if digest != record.get("sha256"):
        print(
            "[check] FAIL sha256 does not match SOURCE.json "
            f"({digest[:12]} != {str(record.get('sha256'))[:12]})",
            file=sys.stderr,
        )
        return 1
    version_file = VENDOR_DIR / VERSION_NAME
    if not version_file.is_file() or version_file.read_text(encoding="utf-8").strip() != record.get("version"):
        print(f"[check] FAIL {VERSION_NAME} does not match SOURCE.json", file=sys.stderr)
        return 1
    if facts["externalPeers"] != record.get("externalPeers"):
        print(
            "[check] FAIL external peers "
            f"{facts['externalPeers']} != SOURCE.json {record.get('externalPeers')}",
            file=sys.stderr,
        )
        return 1
    if facts["unresolvedRequires"] != record.get("unresolvedRequires"):
        print(
            "[check] FAIL unresolved runtime requires "
            f"{facts['unresolvedRequires']} != SOURCE.json {record.get('unresolvedRequires')}",
            file=sys.stderr,
        )
        return 1
    print(
        f"[check] ok {record.get('package')} {record.get('version')} ({record.get('ref')}) "
        f"{facts['bytes']} bytes; peers {', '.join(facts['externalPeers'])}; "
        f"inlined {', '.join(record.get('bundledDependencies') or [])}"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", help="path to a @ctrixin/pi-btw checkout")
    parser.add_argument("--tarball", help="path to an unpacked npm tarball (…/package)")
    parser.add_argument("--ref", default="", help="git ref HEAD must equal (checkout source only)")
    parser.add_argument("--check", action="store_true", help="validate the vendored file, write nothing")
    parser.add_argument("--verify", action="store_true", help="load the bundle in the installed pi")
    args = parser.parse_args()

    if args.check:
        return _check()

    raw_source = args.tarball or args.source
    if not raw_source:
        raise SystemExit("pass --source, --tarball or --check")
    source = Path(raw_source).expanduser().resolve()
    manifest = _package_manifest(source)
    version = str(manifest["version"])
    package = str(manifest["name"])

    if args.tarball:
        ref, commit = f"npm:{package}@{version}", ""
        if not (source / "node_modules").is_dir():
            raise SyncError(
                f"{source}/node_modules is missing; the bundle has to inline its "
                "dependencies, so run npm install in the unpacked tarball first"
            )
    else:
        ref, commit = _resolve_ref(source, args.ref)

    text, metafile = build_bundle(source, ref, version, package)
    facts = verify_bundle(text, metafile)
    esbuild_version = _run([_esbuild_bin(source), "--version"]).stdout.strip()
    VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    bundle_path = VENDOR_DIR / BUNDLE_NAME
    bundle_path.write_text(text, encoding="utf-8", newline="\n")
    digest = hashlib.sha256(bundle_path.read_bytes()).hexdigest()
    (VENDOR_DIR / VERSION_NAME).write_text(f"{version}\n", encoding="utf-8")
    (VENDOR_DIR / NOTICES_NAME).write_text(
        _third_party_notices(source, set(facts["bundledDependencies"]), package),
        encoding="utf-8",
    )
    for name in ("LICENSE", "NOTICE"):
        if (source / name).is_file():
            (VENDOR_DIR / name).write_text(
                (source / name).read_text(encoding="utf-8"), encoding="utf-8"
            )
    record = {
        "package": package,
        "version": version,
        "ref": ref,
        "commit": commit,
        "entryPoint": _entry_point(source),
        "upstream": UPSTREAM_PACKAGE,
        "esbuild": esbuild_version,
        "pi": _pi_version(),
        "sha256": digest,
        "bytes": facts["bytes"],
        "externalPeers": facts["externalPeers"],
        "bundledDependencies": facts["bundledDependencies"],
        "unresolvedRequires": facts["unresolvedRequires"],
    }
    (VENDOR_DIR / SOURCE_NAME).write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    print(
        f"[sync] {bundle_path.relative_to(ROOT_DIR)} {facts['bytes']} bytes "
        f"sha256={digest[:12]}… from {package} {version} ({ref}); "
        f"inlined {', '.join(facts['bundledDependencies']) or 'nothing'}"
    )
    if facts["unresolvedRequires"]:
        print(
            "[sync] WARN the bundle can only resolve these at runtime, so they are "
            f"absent for MMS: {', '.join(facts['unresolvedRequires'])}. "
            "Confirm the fork never reaches them before shipping (see T3-REPORT)."
        )

    if args.verify:
        verify_loads(bundle_path)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SyncError as exc:
        print(f"[sync] {exc}", file=sys.stderr)
        raise SystemExit(2)
